### ISSUE TITLE
Support multiple annotators on one page

### ISSUE THREAD

**Issue by pudo** [openannotation/annotator#131]
I'm trying to set up multiple annotators on a single page using this snippet: https://gist.github.com/94e89ba444d609326ccd

As it is, this produces a working annotator for the first element and will just cancel any selection I perform for all others. 

The page is essentially: http://offenesparlament.de/plenum/17/166 - I need to set them up separately so each can have a canonical URI; as you may see this is not actually a proper text but a solr search result page. 

Any help would be appreciated!

**Comment by melissajeon** [comment]
Hi @nickstenning ,

I've done what you provided with the storage part(https://gist.github.com/2645644).

I've two sections and I can get "i" from the paragraph when I save the annotator. 
However, the issue I am facing is when I save the annotator in the first section. The next time I load the page, the annotator is duplicated in the second section. Even though, I only annotate the first section only.

What am I missing? Do you have a working example on how to use multiple annotators on a single page with storage? Appreciate any helps with this.

**Comment by tilgovi** [comment]
@melissajeon this project is pretty inactive, but my guess is that your search is returning all the annotations and not filtered by paragraph. I would check the network tab in your dev tools to see how the search API is called when you pass `paragraph: i` and see whether you're getting the expected results.

**Comment by melissajeon** [comment]
Hi @tilgovi ,

Thanks for your advice. 
I finally understand how to use the code correctly.
It's all working good! thank you so much!
