### ISSUE TITLE
use annotator to do offset Google Docs style comments (inside an editor)

### ISSUE THREAD

**Issue by holtzermann17** [openannotation/annotator#197]
I don't think there are any open source tools for "offset" comments (like in Google Docs).  It seems like Annotator would be a good candidate tool for this.  Moreover, it would presumably be an editor-independent solution, if I understand how it works correctly.  However, the glue-code to get this running on top of an editor (like ACE or Etherpad) would be fairly non-trivial.

**Comment by JohnMcLear** [comment]
FWIW I got margin comments working in Etherpad.

**Comment by tilgovi** [comment]
@JohnMcLear if you drop a link to it on the mailing list I'm sure there will be interest.

**Comment by hokster7** [comment]
Also very interested in a Google-Docs-style annotation widget (in React, say!)
