### ISSUE TITLE
Have store plugin handle 400 and 403

### ISSUE THREAD

**Issue by mattflaschen** [openannotation/annotator#237]
Currently, there is special handling for 401, 404, and 500 (https://github.com/okfn/annotator/blob/master/src/plugin/store.coffee#L492)

However, 400 and 403 are both also useful.  400 is used for invalid requests.  Although 401 is similar to 403, 401 responses are supposed to have WWW-Authenticate.  403 allows responding with an immediate failure without WWW-Authenticate.

This is similar to issue #5, but that's been closed for a long time, so I didn't comment there.

**Comment by tilgovi** [comment]
It looks like the `HttpStorage` class on master has support for 400, 401, 403, 404, and 500. I think that means we can close this.
