### ISSUE TITLE
Improve the positioning of the editor/viewer if it opens off screen

### ISSUE THREAD

**Issue by aron** [openannotation/annotator#28]
The viewer and editor should always appear fully on the screen. i.e flip the editor upside down or to the right if necessary.

**Comment by aju9316** [comment]
I am facing this issue but with Adder.

The adder always open above the text selected, if the text is right at the top of window then the adder goes out of viewport.

Screenshot attached:
![image](https://user-images.githubusercontent.com/11446292/38933413-7b873f78-4336-11e8-8426-fcae342dfbad.png)


any suggestions to make this work properly?

Opened an issue [here](https://github.com/openannotation/annotator/issues/686)
