### ISSUE TITLE
color-coding annotated text by tagtype

### ISSUE THREAD

**Issue by SumeetSandhu** [openannotation/annotator#309]
I am a newbie to HTML/CSS/JS - looking for fastest way to modify the annotator to: color code the annotated text (not the annotations) by tag type. Eventually, I would also like to present a preset menu of tags and associated colors to the user. 

If I could get a hold of all annotations and their tags, I can simply write a function that changes the color of each annotation based on its tag (this sort of works but the class "annotator-hl" may conflict with my newly defined color classes "annotator-hl-color_i").
Related questions: 
(1) Using precompiled files in annotator-full-1.2.7, how can I grab all the annotations on a page when the page reloads? (note that i can grab individual annotations using annotator events - instead I am looking to grab all annotations). How do I create the path to where my annotations are stored on http://annotateit.org/ ?
(2) If I can't do (1), how do i compile the annotator-master makefile using Webstorm 7.0?

**Comment by Nirvanatin** [comment]
Please could you provide the link for this discussion? There used to be a [plugin](https://github.com/ezietsman/annotator/blob/master/src/plugin/categories.coffee) for this purpose.  It would be very useful to have this feature. It has been requested here as well: https://github.com/openannotation/annotator/issues/493
