### ISSUE TITLE
Widget dragging does not stay with mouse

### ISSUE THREAD

**Issue by dmliao** [openannotation/annotator#342]
Behavior also crops up on the online demo. The first time you open up the annotation widget on a page, you can drag it normally. Opening up a second or a third widget on the same page causes it to behave oddly, moving faster than the mouse on drag.

**Comment by nandita121189** [comment]
@nickstenning 
According to me this issue is not resolved yet. Its even replicable on your demo page (http://annotatorjs.org). Please can you look into it. 

Do I need to add a new issue or will you re-open this issue only ?

Thanks

**Comment by tilgovi** [comment]
This issue was closed in favor of #341 which was closed as fixed. It may be that we just have not made a release on the v1.2.x branch since then.

I'll see what I can do about pushing that out.

**Comment by nandita121189** [comment]
@tilgovi Ok Thanks. Please acknowledge this issue when its done.
