### ISSUE TITLE
More helpful error messages from Auth plugin

### ISSUE THREAD

**Issue by nichtich** [openannotation/annotator#363]
It took me some time to find out that 3rd party cookies for http://annotateit.org/ must be enabled and how to to this. The error message 

    Couldn't get auth token:
    Please go to http://annotateit.org/ to log in!`

was not very helpful, the link is not even clickable. Maybe the message should better be

    Couldn't get auth token: 
    Please <a href="http://annotateit.org/user/log">login</a>
    and enable 3rd party cookies for annotateit.org!

After enabling 3rd party cookies and loggin in, the error message is

    Sorry we could not search the store for annotations

This is not very helpful neither. Some hints how to fix this would be nice.

It's clear to me that annotator is independent from annotateit.org, but it should be easy to set up a website with the latter to start with before one is going to set up his own storage server.

**Comment by tilgovi** [comment]
Bump for this issue. I've been cleaning out issues today since the 2.0 alpha has been released, but I think this is still a good one.

We should:

- Review the error messages for clarity
- Remove the exclamation points that are so unfriendly and panicky

**Comment by tilgovi** [comment]
Actually, I think this is close-able. The auth plugin is no longer in core at all and the store messages seem sensible.
