### ISSUE TITLE
Not working on google map

### ISSUE THREAD

**Issue by hirpara** [openannotation/annotator#370]
Annotator is not working on google map.
![image](https://cloud.githubusercontent.com/assets/5242955/2774161/9729654c-cab0-11e3-8312-4a31511dddcc.png)

after annotator load screen become white.

**Comment by tilgovi** [comment]
I'm going to close this issue. @hirpara if you can reproduce it with the 2.0 alpha we can re-open this, but it should be gone now that we don't use a wrapper div.
