### ISSUE TITLE
Anchor annotations to the closest ancestor ID?

### ISSUE THREAD

**Issue by canadaduane** [openannotation/annotator#394]
I realize there is a group working on making annotations "stick" better when the underlying HTML structure changes; however, for my immediate needs it seems like anchoring annotations to the closest ancestor ID is a huge win over the current docroot-to-node spanning xpath. I've made a patch that achieves this, but don't know if it would be useful to others. It's backwards compatible with existing annotation xpaths.

https://github.com/wordtreefoundation/annotator/commit/c28a03b2500af0570da394d4411ea138e3cd0565

**Comment by luxio** [comment]
@canadaduane  thank you so much for sharing this. This was exactly what I was looking for. 👍🏻
