### ISSUE TITLE
CSS zoom breaks annotation placement

### ISSUE THREAD

**Issue by trnelson** [openannotation/annotator#399]
In testing with Annotator, I notice that when applying a CSS zoom to an area of HTML when encompasses an annotator object, the placement of the popup is thrown off by a significant amount. As an example, an outer div with zoom: 0.75; and a div inside that configured as an annotator. When selecting text, the popup appears very far to the upper left of the selection area.

**Comment by tilgovi** [comment]
Zoom is a non-standard CSS property. I'm going to close this as I don't think we'll fix this. If you come up with a creative way to solve it, feel free to share your work.
