### ISSUE TITLE
Remove obsolete workaround for PhantomJS bug

### ISSUE THREAD

**Issue by csillag** [openannotation/annotator#403]
We have [this workaround](https://github.com/openannotation/annotator/blob/3359eabb13fa7e422174df76cba421c5c87d4421/src/util.coffee#L53) in the code, to avoid problems caused by https://github.com/ariya/phantomjs/issues/11479. 

But that problem has been [fixed](https://github.com/ariya/phantomjs/issues/11479#event-147633535) in PhantomJS 2.0 - so we can remove this workaround, as soon as PhantamJS 2.0 is actually released.

**Comment by tilgovi** [comment]
I think this is gone on master.
