### ISSUE TITLE
Not functional on ehow.com

### ISSUE THREAD

**Issue by orschiro** [openannotation/annotator#445]
I just noticed that after selecting a text, the small pop-up for text highlighting/commenting does not show up. 

The website: http://www.ehow.com/info_8077948_differences-between-invention-innovation.html

Can someone confirm this?

Thanks!

**Comment by tilgovi** [comment]
Can you confirm this on the recent 2.0 alphas? Or does this only affect 1.2.x?

**Comment by orschiro** [comment]
@tilgovi,

Thanks for your follow-up. I just tested the bookmarklet again on the above website and it is working without a flaw! :+1: 

Thanks!

Robert

**Comment by rvaghel123** [comment]
Get best Price quotes for Relocation Service Hyderabad.Visit:-
http://www.movers5th.in/packers-and-movers-hyderabad/

**Comment by rvaghel123** [comment]
Get best Price quotes for Relocation Service in Bangalore.Visit:-
http://www.movers5th.in/packers-and-movers-bangalore/

**Comment by rvaghel123** [comment]
Get best Price quotes for Relocation Service in Pune.Visit:-
http://www.movers5th.in/packers-and-movers-pune/

**Comment by rvaghel123** [comment]
Get best Price quotes for Relocation Service in Mumbai.Visit:-
http://www.movers5th.in/packers-and-movers-mumbai/

**Comment by rvaghel123** [comment]
Get best Price quotes for Relocation Service in Delhi.Visit:-
http://www.movers5th.in/packers-and-movers-delhi/
