### ISSUE TITLE
In Arabic texts, when i select one letter it get separated from it's word.

### ISSUE THREAD

**Issue by bashartalafha** [openannotation/annotator#473]
Dear,

I hope everything is going well, my name is Bashar Talafha, I am currently studying for my masters degree in computer science in Jordan University of Science and Technology.
I have downloaded the "Annotator" tool from http://annotatorjs.org, and i want to use it in arabic, when i select a full word or all sentence it works fine, but when i select one letter it get separated from it's word.
please could you help me to solve this problem to keep the arabic word as it is.
kindly check the attached image to see what i exactly mean.
![4 2](https://cloud.githubusercontent.com/assets/10385096/5604236/251e0c2e-93b8-11e4-9354-a77966dc2ea0.jpg)

Best Regards,
Bashar Talafha

**Comment by nickstenning** [comment]
Hi Bashar. Thanks for this example. This is unfortunate but unavoidable using the stock highlighter that comes with Annotator. This highlighter splits highlighted text in the DOM, so if you highlight the nūn in the middle of 

    الزجاج

then you'll get

    <p>الز<span class='highlight'>ج</span>اج</p>

which turns the nūn into an isolated glyph.

I hope we'll be able to resolve this in the not too distant future by using a highlighter which doesn't interfere with the content in this way, but instead draws highlights above it.

**Comment by systemchef** [comment]
In HTML5 the solution for this problem is simple. Instead of using span to highlight the letters, use ruby element.
Check for a quick demo
http://jsfiddle.net/fjz5C/28/
original question at 
http://stackoverflow.com/questions/12886663/why-do-arabic-characters-behave-as-separate-characters-when-styling-single-arabi

http://www.w3schools.com/tags/tag_ruby.asp

It can be added as option in the main code or a plugin could do the job.

**Comment by tilgovi** [comment]
Although reports on SO seem to say otherwise, I just tried, with success, inserting `&zwj;` on the inside and outside of the span on each side. I was hoping that maybe this meant we could use the `content` property and `:before` and `:after` pseudo-elements but that doesn't seem to work.

**Comment by nickstenning** [comment]
I think the solution to this in the medium term is [marks](/nickstenning/marks). Not sure it's worth investing the effort in fixing it in the short term.

**Comment by tilgovi** [comment]
I agree. We should close this.
