### ISSUE TITLE
Plugins are required to implement a destroy method

### ISSUE THREAD

**Issue by baholladay** [openannotation/annotator#475]
In the function "Annotator.prototype.destroy = function() {", the code assumes that all plugins have a destroy method. If one isn't implemented, then the destroy function fails:

            _ref1 = this.plugins;
            for (name in _ref1) {
                plugin = _ref1[name];
                this.plugins[name].destroy()
            }

**Comment by aron** [comment]
Thanks, I've just created a pull request to fix this on the 1.2.x branch.

**Comment by tilgovi** [comment]
Closed by #476
