### ISSUE TITLE
annotationUpdated event not firing after persisting new annotations to the server

### ISSUE THREAD

**Issue by rwhitmire** [openannotation/annotator#482]
I'm having trouble getting an annotation id after persisting data to the server. Having found this previous closed issue: https://github.com/openannotation/annotator/issues/164 - it sounds like the annotationUpdated event is supposed to fire when the store plugin gets a response from the server.

I'm only seeing the annotationCreated event fire (immediately), and the annotationUpdated event fires immediately when I edit an annotation, but not after an annotation has been created and an id is returned from the server. I have verified that after creating a new annotation, the annotation has been updated with the id it was assigned from the server. I'm not sure if it will help or not, but here's a small code sample:

```javascript
Annotator.Plugin.FeedbackDetails = function (element, options) {
    Annotator.Plugin.apply(this, arguments);
};

$.extend(Annotator.Plugin.FeedbackDetails.prototype, new Annotator.Plugin(), {
    events: {
        'annotationsLoaded': 'annotationsLoaded',
        'annotationCreated': 'annotationCreated',
        'annotationUpdated': 'annotationUpdated',
        'annotationDeleted': 'annotationDeleted',
    },

    annotationsLoaded: function(annotations) {
        if (this.options.onAnnotationsLoaded) this.options.onAnnotationsLoaded.call(this, annotations);
    },

    annotationCreated: function(annotation) {
        // fires immediately when an annotation is created
        if (this.options.onAnnotationCreated) this.options.onAnnotationCreated.call(this, annotation);
    },

    annotationUpdated: function(annotation) {
        // fires immedately when an annotation is updated
        // does not fire when a new annotation has been persisted and is returned from the server
        if (this.options.onAnnotationUpdated) this.options.onAnnotationUpdated.call(this, annotation);
    },

    annotationDeleted: function(annotation) {
        if (this.options.onAnnotationDeleted) this.options.onAnnotationDeleted.call(this, annotation);
    },
});
```

**Comment by rwhitmire** [comment]
The above issue exists on 1.2.9

I just tested this issue against the 2.0 source code and the issue seems to be fixed in that version.

**Comment by rwhitmire** [comment]
looking at https://github.com/openannotation/annotator/blob/v1.2.x/src/plugin/store.coffee - I ended up modifying the source as a temporary workaround. I had to add my own event around at line 142.

```javascript
_this.annotator.publish('annotationCreatedXhr', data);
```

and then I'm able to do

```javascript
annotator.subscribe('annotationCreatedXhr', function (annotation) {
    // handle updated annotation here
});
```

I'd make the fix and create a pull request, but I'm sure this isn't a good solution. I tried manually triggering the `annotationUpdated` event, but that puts the plugin into an infinite callback loop. Hence the poorly named custom event.

**Comment by tilgovi** [comment]
I'm glad you found a solution for yourself. I'm going to close this issue. If you feel that's a mistake, please re-open it and we can discuss.

Meanwhile, we have an alpha version of Annotator 2.0 out now, where the events are reworked quite a bit to avoid this confusion. The events have become hooks, which can (optionally!) defer computation using Promises, and the lifecycle hooks like `annotationCreated` run _after_ storage.

http://docs.annotatorjs.org/en/latest/module-development.html#module-hooks

I hope you check it out and give us feedback. Let us know if the migration guide in the documentation is lacking and tell us how it goes if you try to upgrade.

**Comment by ryanwalters** [comment]
This issue still exists in 1.2.10. It's pretty important to have this fixed in the stable version.

**Comment by tilgovi** [comment]
@ryanwalters you are welcome to submit a pull request

**Comment by sonysujatha** [comment]
Is there any example I can look at using the hooks in 2.0.0 version??
