### ISSUE TITLE
CSRF tokens with store requests? 

### ISSUE THREAD

**Issue by timReynolds** [openannotation/annotator#483]
Whats the best approach for providing a CSRF token in store requests? From looking at the source code it seems I should be able to define custom headers in as shown below, however this isn't being passed to the server as I'd expect. 

Anyone tried this before or got any advice?  

```   
  var annElem = $('#document-preview').annotator();
    annElem.annotator('addPlugin', 'Store', {
      prefix: '/api',
      headers: {
        'X-CSRF-Token': TOKEN
      },
      annotationData: {
        'uri': '{{Request::url()}}'
      },
      loadFromSearch: {
        'limit': 20,
        'uri': '{{Request::url()}}'
      }
    });

**Comment by tilgovi** [comment]
Why do you want to provide a CSRF token for these requests? They are often intended to be cross-origin in many depolyments. For instance, the bookmarklet runs on an arbitrary site and makes cross-site requests.

**Comment by timReynolds** [comment]
In this deployment it's not. So I'd like to be able to add a token to the requests.

**Comment by aron** [comment]
`headers` an option for the store plugin, but you can provide headers by setting the `annotator:headers` data key.

```js
var annElem = $('#document-preview').annotator();
annElem.data('annotator:headers', {
  'X-My-Custom-Header': 'CustomValue',
  'X-Auth-User-Id': 'bill'
});
```

https://github.com/openannotation/annotator/blob/v1.2.x/src/plugin/store.coffee#L346-L364
