### ISSUE TITLE
Programmatically create annotations

### ISSUE THREAD

**Issue by axelson** [openannotation/annotator#485]
Is it possible to programmatically create annotations? It seems like it should happen in the store plugin (http://docs.annotatorjs.org/en/v1.2.x/plugins/store.html), but it looks like the store plugin only supports a remote JSON endpoint instead of just providing a local JSON object.

My use case is I have multiple annotation/highlights that I want to do of a sentence, where the phrases to highlight are known in javascript and may overlap, the annotation/tooltip would have specific text for the phrase. The annotations/highlights are read-only.

Am I missing something simple? Or will I need to implement the search url somehow?

**Comment by tilgovi** [comment]
You should be able to call `annotator.setupAnnotation({annotation})`.

**Comment by axelson** [comment]
Thanks, is that documented somewhere? If it was I seem to have missed it.

**Comment by axelson** [comment]
And if it isn't is there a good place I can add it to the documentation?

**Comment by tilgovi** [comment]
API docs for the objects themselves are only in comments in the source.

APIs for this sort of thing are not settled on the master branch, which will become v2, but we will need docs. Thanks for the offer.

**Comment by axelson** [comment]
Thanks for your help I got it working. For anyone else that wants to accomplish this here is a code snippet:

    $('.target-to-annotate').text('apple, banana');
    match = $('.target-to-annotate').text().indexOf('banana');
    $('.target-to-annotate').annotator();
    annotator = Annotator._instances[0];
    var range = Annotator.Range.SerializedRange({start: "", startOffset: match, end: "", endOffset: match + 'banana'.length});
    annotator.setupAnnotation({text: "My tooltip text to display", ranges: [range]});

If there's a better way to get the `annotator` please let me know.

**Comment by tilgovi** [comment]
You can create the instance directly rather than using the jQuery
integration:

```
var el = $("#target-to-annotate")[0];
var annotator = new Annotator(el);
```

**Comment by axelson** [comment]
Ah, thanks that is better

**Comment by manoj-mass** [comment]
@tilgovi  how can we do this in annotator 2.0.
