### ISSUE TITLE
Invoking the annotation programmatically

### ISSUE THREAD

**Issue by systemchef** [openannotation/annotator#487]
How can I invoke the annotation pop-up programmatically on an element?
The scenario is I need to add annotation on a button, and as I can not select the button text in usual way, I want to be using right click handler on hyperlinks and buttons to invoke the same pop up for annotation.
Any clues?
something like 
var el = $("#target-to-annotate")[0];
var annotator = new Annotator(el);
annotator.show();???

**Comment by tilgovi** [comment]
```js
annotator.viewer.element.css({top: ..., left: ...});
annotator.viewer.show();
```

Questions like this are better suited to the dev list, where people who don't actively watch the issues on GitHub may be able to help you faster.

**Comment by tilgovi** [comment]
Replace `viewer` with `editor` if you want to show the editor.
