### ISSUE TITLE
TypeError with v 1.2.10

### ISSUE THREAD

**Issue by shaunagm** [openannotation/annotator#489]
Thanks for releasing 1.2.10.  However it's introducing an error for me:

<code>TypeError: $(...).parents(...).addBack is not a function</code>

I get this error when I click anywhere on the page being annotated.

**Comment by tilgovi** [comment]
What version of jQuery?

**Comment by tilgovi** [comment]
This function doesn't exist before recent versions of jQuery. It superceded the `andSelf()` function. Older Annotator releases used `andSelf()` but if you're using one of the most recent couple versions (1.2.9+, I think), you'll need a newer version of jQuery or the jQuery migrate addon.

**Comment by shaunagm** [comment]
I'm using 1.7 -- I copied the reference from here:
http://docs.annotatorjs.org/en/v1.2.x/getting-started.html

Do you have a recommended version of Jquery?  Happy to switch.

**Comment by tilgovi** [comment]
If you need support for IE 6, 7 or 8, then jQuery 1.11.x, otherwise 2.1.x. The latest, basically.

Sorry for the confusion. I'll leave this ticket open until we update the docs.

**Comment by shaunagm** [comment]
If you'd like, I can update the docs for you, if it's as simple as updating that rst file to say [what you just said](https://github.com/openannotation/annotator/issues/489#issuecomment-76239198).

**Comment by tilgovi** [comment]
That'd be great!

**Comment by shaunagm** [comment]
Here you go: https://github.com/openannotation/annotator/pull/491

Thanks for all the help!
