### ISSUE TITLE
"Destroy" methods gone after minification (1.2.x)

### ISSUE THREAD

**Issue by darth-cheney** [openannotation/annotator#490]
As far as I can tell, the `destroy` methods, both on the `Annotator` instances and the jQuery plugin are minified and therefore unusable when loading the minified version of the library.

**Comment by tilgovi** [comment]
I can't reproduce this.

**Comment by tilgovi** [comment]
What annotator.min.js are you using?

**Comment by darth-cheney** [comment]
Yup. Nevermind, must have been one that I uglyfied myself from source.

**Comment by darth-cheney** [comment]
Was using 1.2.9 fyi
