### ISSUE TITLE
Is it possible to change to the color of the annotations retrieved from Storage server

### ISSUE THREAD

**Issue by hongjiedai** [openannotation/annotator#493]
I have used the Store plugin and retrieved data from my server.
Is there a way to change the highlighting color?

I tried to use 
$('.annotator-hl')

But it cannot find any instances.

**Comment by XigenBen** [comment]
+1 – Would be great to be able to mark text as 'deleted' with a strikethrough as well.

**Comment by hongjiedai** [comment]
Or is it possible to register an event to get the notification when the Store plugin update the content?

**Comment by hongjiedai** [comment]
I don't know whether there are other ways but I find a solution by overriding the _onLoadAnnotationsFromSearch defined in the Store plugin in which I add my highlights definition.

**Comment by tilgovi** [comment]
There is no provided feature for customizing the colors of individual highlights.
