### ISSUE TITLE
Page refresh problem when editing/removing annotations with multiple annotators for elements with the same class

### ISSUE THREAD

**Issue by hongjiedai** [openannotation/annotator#497]
I have successfully added multiple annotators by using $(".title").annotator();
It works perfectly when I added new annotations,
However, when I try to edit or remove any of the existing annotations, the page was automatically refreshed and  I cannot modify any annotations (can be removed but the page will reload).

The situation won't appear when I add annotators by using $("div").annotator() or other selectors without "class".

Is it a bug?

**Comment by hongjiedai** [comment]
I don't know whether the problem is specific for my case (I used annotator in developing my Chrome extension). I solved the problem by modify the 
*Util.preventEventDefault* function to prevent event propagate
```javascript
Util.preventEventDefault=function(event){if(!event)event=window.event;
// ... 
'''

**Comment by tilgovi** [comment]
Preventing the default action should be all that's needed to prevent page navigation when the links for submit, edit, etc are clicked. If you can provide a test case or sample code that reproduces your issue, please re-open.
