### ISSUE TITLE
Using offline plugin - Loading on multiple pages

### ISSUE THREAD

**Issue by oxhey** [openannotation/annotator#500]
I'm adding annotations to reveal.js presentations . 

I have added the offline plugin and used some suggested that would make the plugin only load annotation from the reveal presentation that they came from.

The problem is that an annotation from one presentation still loads on another.

jQuery('Lecture 1').text(); is changed to jQuery('Lecture 2').text(); in the other reveal presententaion.
```
    <script>
    var content = jQuery(".reveal").annotator();
    content.annotator('addPlugin', 'Offline', {
      setAnnotationData: function (ann) {
    if (!ann.pageName) {
      ann.pageName = jQuery('Lecture 1').text(); // Use the page title
    }
  },
  shouldLoadAnnotation: function (ann) {
    return ann.pageName === jQuery('Lecture 1').text();
  },
      online:  function () {
        jQuery("#status").text("Online");
      },
      offline: function () {
        jQuery("#status").text("Offline");
      }
    });
    var annotator = content.data('annotator');

    jQuery("#clear-storage").click(function () {
      if (annotator) {
        annotator.plugins.Offline.store.clear()
      }
    });
    </script>
```

**Comment by nickstenning** [comment]
For support and general enquiries, please use the [`annotator-dev` mailing list](lists.okfn.org/mailman/listinfo/annotator-dev).

**Comment by oxhey** [comment]
I did . No reply

**Comment by tilgovi** [comment]
@oxhey it's only been two days. Please be patient.

**Comment by oxhey** [comment]
Problem fixed

**Comment by tilgovi** [comment]
Great!

**Comment by jumpjack** [comment]
Fixed how/where?
How do I select where to load annotations from for current page?
