### ISSUE TITLE
Annotator not working 

### ISSUE THREAD

**Issue by khayati114** [openannotation/annotator#501]
Hi 
I have added annotator-full.min.js in my html page to use but the annotations aren't coming up. I am testing the same on FF V 36.Below is the header code -

<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="http://resources/demos/style.css">
<script src="http://assets.annotateit.org/annotator/v1.2.5/annotator-full.min.js"></script>
<link rel="stylesheet" href="http://assets.annotateit.org/annotator/v1.2.5/annotator.min.css">
<script>
jQuery(function ($) {
    $('body').annotator();
});
</script>

**Comment by nickstenning** [comment]
For support and general enquiries, please use the [`annotator-dev` mailing list](lists.okfn.org/mailman/listinfo/annotator-dev).
