### ISSUE TITLE
Previously created annotations not loaded on the web page even though search API returns correct range data for the annotation

### ISSUE THREAD

**Issue by apurvajalit** [openannotation/annotator#504]
I have implemented my own store backend with the all the required APIs implemented. I am using loadFromSearch due to which annotator when initialized, searches for the annotations for that page for a user. I checked for the response returned and it seems correct and exactly the same as that was sent when annotation is created except that fields like created, updated and ID are added in the response. On stepping closely over the annotatorjs, I found that an **exception** is thrown in function *setupAnnotation* when this statement is executed: *normedRanges.push(Range.sniff(r).normalize(root))*. The error message is :**"Couldn't find offset undefined in element /p[1]"** which leads to execution of this statement **this.publish("rangeNormalizeFail", [annotation, r, e])**

The request on creation is as *{"ranges":[{"start":"/p[1]","startOffset":884,"end":"/p[1]","endOffset":899}],"quote":"Information Age","text":"AnnotationText","tags":[],"uri":"http://localhost:5555/Home/TestPopup","user":2}*

Response:
*{"total":1,"rows":[{"ranges":[{"start":"/p[1]","startoffset":884,"end":"/p[1]","endoffset":899}],"quote":"Information Age","text":"AnnotationText","tags":[],"uri":"http://localhost:5555/Home/TestPopup","user":2,"id":10040,"created":"2011-05-24T18:52:08.036814","updated":"2011-05-24T18:52:08.036814"}]}*

I have posted this issue on the mailing list too, but have not received any responses. Hence treating it as an issue.

**Comment by tilgovi** [comment]
It looks like the case of `startOffset` changed. Your request says `startOffset` but your response says `startoffset`. The first is correct, I think.

**Comment by apurvajalit** [comment]
It finally worked!!! Thank you so much.. you rock!

Thanks,
Apurva Jalit
