### ISSUE TITLE
Store plugin documentation 404 not found

### ISSUE THREAD

**Issue by Luperi** [openannotation/annotator#507]
This link does not work http://docs.annotatorjs.org/en/latest/storage.html

**Comment by tilgovi** [comment]
Where did you find that link so that we may correct it?

**Comment by tilgovi** [comment]
Here's the v1.2.x documentation: http://docs.annotatorjs.org/en/v1.2.x/storage.html

**Comment by Luperi** [comment]
If I have some question about store plugin what can I do?? In particoular I'm developing a symfony2 bundle for annonatorjs and I've correctly implemented my own store plugin, but it's not clear enought to me how to javascript-side interrogate search api. How can I populate the html page with all the annotations returned in JSON format?

Thank you and sorry for my bad english. 

Best regards

**Comment by tilgovi** [comment]
Perhaps if you can share your code and more details about the problems you have someone can help you. It is possible you will get more responses by posting to the mailing list. That is the preferred method of reaching the community (non-maintainers who might be able to help don't necessarily watch github).

You can find the list here: https://lists.okfn.org/mailman/listinfo/annotator-dev

Before I close this, though, could you tell me where you found the link to the documentation that gave you a 404? I would like to correct the link.

**Comment by Luperi** [comment]
At this page https://github.com/openannotation/annotator/wiki/Store-Plugin

**Comment by tilgovi** [comment]
Cool. I'm just going to link to the root of the docs from there. Thanks! And please do email the list with your questions, we'll be glad to help.
