### ISSUE TITLE
How to build 2.0 master for use in plugin projects

### ISSUE THREAD

**Issue by btburton42** [openannotation/annotator#514]
I'm currently working on developing a plugin for annotator. What is the current plugin development workflow that other dev's are following for working with the current Master branch? I see that we can build HEAD with `npm install` && `npm start` but is there a tool to export this for use in other repos?

**Comment by tilgovi** [comment]
It had not been shipped yet, but we just sprinted hard on the documentation and tried to get things in a reasonable state.

`npm install annotator@2.0.0-alpha.2` should now work.
