### ISSUE TITLE
es.init_app

### ISSUE THREAD

**Issue by dewolfe001** [openannotation/annotator#517]
I have been trying to debug my install of the annotator application. It won't run nor will it pass its run_tests.py. I have tried to find if anyone else has experienced the same problems, but it looks this is uncommon.

<pre>
======================================================================
ERROR: test suite for <module 'tests' from '/var/www/annotateit-master/tests/__init__.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/var/www/annotateit-master/tests/__init__.py", line 6, in setup
    app = annotateit.create_app()
  File "/var/www/annotateit-master/annotateit/__init__.py", line 39, in create_app
    es.init_app(app)
AttributeError: 'ElasticSearch' object has no attribute 'init_app'
-------------------- >> begin captured logging << --------------------
annotateit: DEBUG: Creating annotateit application
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 0 tests in 0.394s

FAILED (errors=1)
</pre>

If I have a vanilla install of Annotator, what piece(s) am I missing?

Thanks in advance,

Shawn

**Comment by tilgovi** [comment]
This sounds like a question for https://github.com/openannotation/annotator-store or https://github.com/openannotation/annotateit.

It looks like you're running annotateit. I suspect there's a version pinning problem and annotateit relies on an old version of annotator-store but it doesn't specify a specific enough version in its dependencies.

Can you explain a bit more what you're trying to do, what you mean by "vanilla install of Annotator", etc?
