### ISSUE TITLE
Performance Slowness when initiating Annotator in Chrome

### ISSUE THREAD

**Issue by baholladay** [openannotation/annotator#524]
Modifications made to the DOM when loading the annotator causes Chrome to have to recalculate all inner elements when it adds the "annotator-wrapper" div inside the selected text div (e.g. $(".text").annotator(options);). This recalculation is triggered by JQuery's call to "getComputedStyle " and can be extremely slow (20+ seconds) when dealing with large bodies of text. There is no way to avoid this recalculation other than to do the following:

I have found that you can just add the HTML yourself before you call the annotator constructor:

HTML:

<div class="text">
  <div class="annotator-wrapper">
     Text text text blah blah
 </div>
</div>
<script>
$(document).ready(fuction(){$(".text").annotator(options);});
</script>

And modify the annotator javascript to not wrap:

@@ -839,7 +857,7 @@
         Annotator.prototype._setupWrapper = function() {
             this.wrapper = plagJQ(this.html.wrapper);
             this.element.find("script").remove();
-            this.element.wrapInner(this.wrapper);
+        //    this.element.wrapInner(this.wrapper);
             this.wrapper = this.element.find(".annotator-wrapper");
             return this
         };

**Comment by tilgovi** [comment]
The master branch no longer uses a wrapper and a change this large is not going to land on the v1.2.x branch anymore. I hope you don't mind if I simply close this.

**Comment by baholladay** [comment]
No problem! This can be here for people who run into this issue until the master branch is released.

**Comment by baholladay** [comment]
The important point of this ticket is that the annotator constructor doesn't modify the DOM. Sounds like this is the case for master, correct?

**Comment by tilgovi** [comment]
Correct.
