### ISSUE TITLE
Performance Slowness with Flatten function

### ISSUE THREAD

**Issue by baholladay** [openannotation/annotator#525]
I found the the Flatten function is extremely slow when dealing with 40k+ text nodes. The issue is that it is using the javascript "concat" function, which is extremely slow. This function works 1000x faster and returns the same result:

```javascript
return jq.map(function() {
        	function isArray(obj) {
        		return toString.call(obj) === '[object Array]';
        	};

        	function flatten(branch, flat, max, depth) {
        		flat = flat || [ ]; max = max || 1;
        		depth = ( depth ? depth + 1 : 1);
        		for(var i in branch) {
        			if(isArray(branch[i])) {
        				if((max < 0) || (depth <= max)) {
        					flatten(branch[i], flat, max, depth);
        				} else { flat.push(branch[i]); }
        			} else { flat.push(branch[i]); }
        		}
        		return flat;
        	};        	
            return flatten(getTextNodes(this), [], -1, -1);
        })

```

**Comment by tilgovi** [comment]
@baholladay this code has moved to openannotation/xpath-range.
Could you open a pull request there, please?

**Comment by tilgovi** [comment]
Actually, @wjt has already opened a PR over there that rewrites the only function that uses `flatten`, openannotation/xpath-range#9. So I will simply close this. Thanks for your efforts, though!

**Comment by baholladay** [comment]
Good to hear! Thanks for following up
