### ISSUE TITLE
Documentation Issue: Editor vs. Viewer on editorExtension

### ISSUE THREAD

**Issue by richard-schwab** [openannotation/annotator#535]
On this page:
http://annotator.readthedocs.org/en/latest/api/ui/tags.html?highlight=tags#annotator.ui.tags.editorExtension

your editor example should read: 
> editorExtensions: [annotator.ui.tags.editorExtension],   

rather than 
> viewerExtensions: [annotator.ui.tags.viewerExtension],

**Comment by tilgovi** [comment]
Thanks! Would you like to submit a pull request?

**Comment by tilgovi** [comment]
Closed by #539
