### ISSUE TITLE
Unable to edit / delete a note when attempting to create a custom store with django.

### ISSUE THREAD

**Issue by richard-schwab** [openannotation/annotator#536]
Hello,
I'm working on adapting this project for django here: https://github.com/richard-schwab/annotatorjs-django

Apologies if this is the wrong method you like to get your attention. I am simply stuck trying to get annotatorjs to show the buttons for edit / delete after I create a note. Any suggestions? 

Great project btw, once I get this working it will be more helpful than you can imagine for my work.

**Comment by tilgovi** [comment]
If you're using the Permissions plugin you will need to ensure that the annotations have the proper values in the permissions field. See these docs and let me know if it helps: http://docs.annotatorjs.org/en/v1.2.x/plugins/permissions.html

**Comment by richard-schwab** [comment]
This is most useful to revisit as in my own project, I plan to have multiple users. Let me try this but I'm curious, it says "By default all annotations are publicly viewable/editable/deleteable. We can set our own permissions using the options object." I guess this is why I overlooked it prior. Will let you know results when I can.
