### ISSUE TITLE
Disqus or facebook comment integration

### ISSUE THREAD

**Issue by aloncarmel** [openannotation/annotator#538]
I'm interested in developing an integration with disqus or facebook comments, mainly letting users display a disqus comment embed inside the annotation bubble and changing the size of it.

How would one approach this kind of task?

**Comment by tilgovi** [comment]
I think you would want to create your own widget or two from scratch, modeled after the viewer/editor. Check out `src/ui/widget.js` as a starting point and see what `src/ui/viewer.js` and `src/ui/editor.js` do.

In the future, the mailing list is a better place to ask questions and start discussions like this.
