### ISSUE TITLE
Using Annotation Tags autocomplete in v2.0

### ISSUE THREAD

**Issue by sharmeen-rehan-confiz** [openannotation/annotator#540]
For v1.x the way to add autocomplete to tags is rather straight forward. However I can't see any documentation detailing how to add autocomplete in v2.0. I'd appreciate some help regarding this.

**Comment by tilgovi** [comment]
First add the tags extension:

```javascript
var app = new annotator.App();
app.include(annotator.ui.main, {
  element: document.body,
  editorExtensions: [annotator.ui.tags.editorExtension],
  viewerExtensions: [annotator.ui.tags.viewerExtension]
});
```

Then you should be able to get the tags field: `annotator.util.$('.annotator-editor input').first()`.

Or you could make your own viewer/editor extensions by looking out how those functions from the tags module are implemented, and you can handle this however you like.
