### ISSUE TITLE
Does not work on android chrome

### ISSUE THREAD

**Issue by gravi2** [openannotation/annotator#541]
Android: 5.0.2
Phone: Samsung S6 edge
Browser: Chrome 43.0.2357.93

Steps:
1. Visit annotatorjs.org
2. try touching any of the yellow highlighted lines.

Issue:
Annotations show and disappear. They don't stay open.

**Comment by tilgovi** [comment]
The default UI is not designed for mobile. Annotator can be customized with new UI by including a different UI module than the default, `annotator.ui.main`.

I would love to see mobile UI modules published by the community or pull requests.
