### ISSUE TITLE
Markdown Extension not working with showdown.js

### ISSUE THREAD

**Issue by bryantt927** [openannotation/annotator#542]
In annotator v2.0, could you specify what version of showdown.js you are using? Since it is not working with the latest [showdown.js] (https://cdn.rawgit.com/showdownjs/showdown/1.1.0/dist/showdown.min.js) version. 

Even if I had the showdown.js in my js files, it keeps throwing the warning that I must include showdown to use markdown plugin.

I have tried a few things with console.log and it seems like the render function is not being called. 

``` javascript
var render = exports.render = function render(annotation) {
                var convert = util.escapeHtml;
                if (g.Showdown && typeof g.Showdown.converter === "function") {
                    convert = (new g.Showdown.converter).makeHtml
                }
                if (annotation.text) {
                    return convert(annotation.text)
                } else {
                    return "<i>" + _t("No comment") + "</i>"
                }
            };
```
I get the error that makeHtml is not a function. 

Store plugin is the only other plugin that we are using.  We are using it as part of a Drupal 8 site.

Thanks for any help.  We'd love to be able to include images and links in the annotations.

Todd
(Dickinson College)

**Comment by bryantt927** [comment]
Hi 
I got it to work, But only by copy and pasting the showdown.js code into the annotator.min.js file.

Thanks,
Todd
(Dickinson College)

**Comment by tilgovi** [comment]
I've just pushed a branch called 'remove-get-global'. Please give that a try.

**Comment by tilgovi** [comment]
#527

**Comment by tilgovi** [comment]
Give it a try now. The master branch is updated.

**Comment by tilgovi** [comment]
The problem was actually that the markdown plugin hadn't been updated since the Showdown 1.0 release. It's now fixed on master.

**Comment by bryantt927** [comment]
You just made an English professor very happy.  I don't know how to minify the file for the project, but it can wait for the next release.

Thanks again.
