### ISSUE TITLE
Create groups

### ISSUE THREAD

**Issue by forteller** [openannotation/annotator#544]
I need a tool to annotate websites to collaborate with a group of people. That is: I want some people to see my annotations, but not everyone. I've only found one tool that lets me do that, but I's bulky and not Free Software. 

If you could implement this feature, you would be leaps ahead of all competition it seems to me.

Thank you!

**Comment by AndrewMagliozzi** [comment]
@forteller Thanks for the message.  Annotator definitely supports collaborative annotation as well as auth and roles.  You just have to configure it properly.  Have you looked at [our documentation](http://docs.annotatorjs.org/en/v1.2.x/)?

This discussion is probably better for our mailing list than github tickets.  You can [join the discussion here](https://lists.okfn.org/mailman/listinfo/annotator-dev).  As such, this ticket should be closed.

**Comment by tilgovi** [comment]
From the point of view of Annotator, this is already done in some sense.

There are things that could be built. For instance, there is no built-in UI for multiple membership, allowing users to select which group(s) to share an individual annotation with. However, there is a notion of role-based access control lists (positive assertions only). A lot of authorization depends upon the back end, which Annotator does not specify.

As @AndrewMagliozzi said, join the dev list if you want help setting any of this up. I'm going to close this issue, though.
