### ISSUE TITLE
Storing annotations

### ISSUE THREAD

**Issue by PRATHIKSHA1995** [openannotation/annotator#545]
I have hundreds of text documents. Is it possible to store annotations in a database on my own server?

**Comment by tilgovi** [comment]
Yes, please read [the documentation](http://docs.annotatorjs.org/en/v1.2.x/storage.html) and if you have questions ask on [the mailing list](https://lists.okfn.org/mailman/listinfo/annotator-dev).

**Comment by PRATHIKSHA1995** [comment]
Thanks for the help. Will get back on the mailing list.

**Comment by PRATHIKSHA1995** [comment]
I have hundreds of text documents on my website. User can log in and make annotations. The user information is stored in a MYSQL database. How to store annotations made by the user in a MYSQL database? 
Please lead me to the link and help me get started.

Thank you!

**Comment by tilgovi** [comment]
What version of Annotator? Can you explain what you have tried already and what parts of the documentation are confusing?

**Comment by PRATHIKSHA1995** [comment]
I am using annotator 1.2.5. I have tried using store plugin with the prefix pointing to my server. This doesn't seem to work. I get the following error : http://localhost/annotations/search?uri=http%3A%2F%2Flocalhost%2FAnnotation%2Ftest.html . Am I going in the right direction? Please help. 
Thank you!

**Comment by tilgovi** [comment]
I won't be able to see that error because it points at `localhost` so for me that is my machine but for you it is yours.

**Comment by tilgovi** [comment]
Can you post the text of the error?

**Comment by PRATHIKSHA1995** [comment]
Thanks a lot for responding to my questions. It would be better if I explain my problem in detail.
I am using apache server. I have text in sample.html. My current url is http://localhost/sample.html
The name of my database is TEST. I want to insert annotations in this TEST database. In the code for Store plugin in the documentation, what should be the prefix and urls for create, update etc.? Should I write an API on my own? What exactly do you mean by store endpoint on my server?
I have been trying for two weeks and frustrated with no progress in my work. Please help me clear all my confusions and get started.
Thank you!

**Comment by tilgovi** [comment]
You need to write an API, yes. Or perhaps have a look at some of the few already written by others.
https://github.com/openannotation/annotator/wiki#backend-stores

**Comment by PRATHIKSHA1995** [comment]
Thanks a lot for your guidance. I am trying to build the api. Will get back if I have any doubts.

**Comment by PRATHIKSHA1995** [comment]
I am building the api in php. When an annotation is created, my php code responds to the POST method by sending id, indicated by the following code : 
** $obj->id="1";
	echo json_encode($obj); **

But when I check the annotation, I get the json without id appended to it. Example:
**{"text":"helloworld","ranges":[{"start":"","startOffset":2,"end":"","endOffset":7}],"quote":"hello","uri":"http://localhost/Annotation/annotateit.html"}**

How do I get the id in this annoted json data?
Also, to use loadFromSearch, the json must contain a parameter called rows. How do I get the complete json with id and rows parameter? Kindly guide me with all patience.
Thank you!

**Comment by tilgovi** [comment]
When do you mean when you say that you "check the annotation"? In the front end or in some database?

Can you provide the full request/response data and describe what you are doing in more detail?

**Comment by PRATHIKSHA1995** [comment]
I am fetching the json and writing it to a file using the following code : 
```
if($_SERVER['REQUEST_METHOD']=='POST')
{
     $obj->id="1";
     echo json_encode($obj);     //returning id 
     $json = file_get_contents('php://input');      //fetching annotated data
     file_put_contents('newput.txt',$json, FILE_APPEND);     //writing json to file
}

```
When I check the file newput.txt, I get the json the this format without id and row parameters:
**{"text":"helloworld","ranges":[{"start":"","startOffset":2,"end":"","endOffset":7}],"quote":"hello","uri":"http://localhost/Annotation/annotateit.html"}**
Is the way of returning id correct? It should get appended to the json right?
Please help me clarify my doubts. Thank you for responding to my questions.
Thank you!

**Comment by tilgovi** [comment]
I'm not sure, because I'm not fluent in PHP, but it looks like this is what happens:

1) You add "id" to the object
2) You JSON encode that object and echo it back out to the client
3) You *read the input to again*
4) You put that result into the file

I think the problem is with step (3). You or your framework read the data once (somewhere?) into `$obj`. You modify that. But then you read it _again_ from the original 'php://input' (I am only guessing how that works). So you are writing the client request to the file, not your response.

Take some time to read through the other PHP implementations that exist already and see if you can get help from other PHP developers elsewhere if you run into trouble like this.

If you have questions about Annotator, please use the mailing list as I asked before. I cannot promise to provide debugging help in a closed issue here.
