### ISSUE TITLE
Not properly saving uri

### ISSUE THREAD

**Issue by dcgolden** [openannotation/annotator#548]
Annotator 2.0.0-alpha-3, when creating an annotation it is not storing the uri of the page it was created on. It seems to return only the quote, ranges, and text.

**Comment by tilgovi** [comment]
This is the intended behavior. Please use the `beforeAnnotationCreated` hook if you need to add more information to the annotation.

http://docs.annotatorjs.org/en/latest/module-development.html#beforeAnnotationCreated
