### ISSUE TITLE
Issue while downloading

### ISSUE THREAD

**Issue by sulthanallaudeen** [openannotation/annotator#555]
When i download annotator directly and when i try to run the demo.html

i got the error 

Oops! it looks like you haven't built Annotator. "Either download a tagged release from GitHub, or build the package by running `make`

May i know the tags that are available. 

Is it possible to download it using composer ? because i am having composer in my machine.

**Comment by tilgovi** [comment]
I don't know what composer is.

How did you download annotator?

**Comment by tilgovi** [comment]
Bump

**Comment by sulthanallaudeen** [comment]
Ahm, I downloaded directly from github.. i tried to ask whether you provide option to download it via composer.. This is called as composer... https://getcomposer.org/ It is used to download most of the applications directly from github throught the command line..
