### ISSUE TITLE
Possiblity of saving and retrieving annotation on images / pdf 

### ISSUE THREAD

**Issue by sulthanallaudeen** [openannotation/annotator#557]
I want to save and retrieve annotations that are done on the images/pdf.

Note : I want to save and retrieve annotations in my local db, so is it possible to do it without login or signup ?

**Comment by tilgovi** [comment]
Please review the documentation and ask questions on the mailing list. Annotator does not provide support for image annotation, but third party modules may exist or be built to help. With PDF, the story is more complex, and knowing what you actually want to do is important (are you using PDF.js, trying to run Annotator in a scripting environment of some PDF viewer, etc).

In any case, please discuss on the mailing list and try to keep this space for bugs and proposals.

**Comment by tilgovi** [comment]
It is not necessary to create any login ever. Annotator does not require any login. Where and how you store your annotations, and whether that needs authorization, is up to you.
