### ISSUE TITLE
Unable to create an annotation on top of a filtered annotation

### ISSUE THREAD

**Issue by phobosultra** [openannotation/annotator#564]
The problem occurs when I select a portion of text which is entirely inside of a filtered annotation (class="annotator-hl-filtered"). In that case the adder will not show up.
In the function `checkForEndSelection()` the routine will exit at the check `isAnnotator()`.
```javascript
[...]
for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
     range = _ref1[_k];
     container = range.commonAncestor;
     if (this.isAnnotator(container)) {
      return
     }
}
[...]
```
(tested with Version 1.2.10)

**Comment by tilgovi** [comment]
It's not currently supposed to be possible to annotate any part of the annotator UI.

**Comment by phobosultra** [comment]
Sorry I don't get this, I am able to create an annotation on top of a (visible) annotation but not on a filtered (invisible) annotation.
Is that right?

**Comment by tilgovi** [comment]
Maybe I misunderstand what you mean. I thought you meant you were trying to annotate the viewer. You mean that you cannot annotate the same text?

**Comment by tilgovi** [comment]
I see. Thanks for the report.

**Comment by phobosultra** [comment]
Tested and it works. Thank you
