### ISSUE TITLE
Replacing 'x' delete icon with something else?

### ISSUE THREAD

**Issue by nikolas** [openannotation/annotator#568]
In the annotator pop-up, the "x" icon could be interpreted as a control to close the window, instead of deleting the annotation. Is there a way to configure this through annotator.js, without changing the internals?

I'm interested in one of the following possibilities:
* Add a warning message of the type: "are you sure you wish to delete this annotation?"
* Substitute the X with the words "delete"
* Substitute the X with a trash can icon.

I'm using Annotator v2.0.0-alpha.3.

**Comment by tilgovi** [comment]
You can override `annotator.ui.viewer.Viewer.itemTemplate`.

**Comment by nikolas** [comment]
thanks!
