### ISSUE TITLE
Switch mouse highlight on / off

### ISSUE THREAD

**Issue by TomThak** [openannotation/annotator#573]
Is it somehow possible to switch on "highlighting" and switch off "highlighting" on some button event?
For example, if the user wants to just select the block of text for copy / paste purposes there is need to create new annotation. I would like to have possibility to swtich annotation process on, when needed and when I want to highlight something in text and otherwise to have it switched off.

I could not find anything like this in documentation.

Thanks!

**Comment by tilgovi** [comment]
The `ui.textselector.TextSelector` extension fires an `onSelection` callback. It's up to you to use the `ui.main` module as a boilerplate for your own UI and use whatever application state you need to decide what to do when a selection occurs.

**Comment by TomThak** [comment]
Understand! Thanks
