### ISSUE TITLE
Annotator 2.0 - Read Only Mode?

### ISSUE THREAD

**Issue by martinkoslof** [openannotation/annotator#580]
Hi there, I am reviewing Annotator 2.0 and so far I'm liking what I see. I currently have javascript similar to the following:

``` javascript
var pageInfo = function (){
          return {
              beforeAnnotationCreated: function(ann){ann.uri = window.location.href;},
        };
 };
 var app = new annotator.App()
       .include(annotator.ui.main, {element: document.body})
       .include(annotator.storage.http, {prefix:'....',urls: {}})
       .include(pageInfo);

app.start()
         .then(function(){
            app.annotations.load({uri: window.location.href});
          });
```

And everything is working fine. I have my server side storage working, I can add, edit and delete annotations and anything which exists loads on start(). What I can't seem to find is the 2.0 equivalent to making the editor READ ONLY.  I know in the legacy version a property of 'readOnly' could be used to make the annotations view only. How can I achieve the same results in the new 2.0 version?  The goal is to check the current user (not included here for simplicity) against server side roles and if they are not allowed to edit or add annotations, they can only hover over and see existing annotations.

Thanks

**Comment by martinkoslof** [comment]
Partially answering my own question. I took a few minutes to look at the source code and try to make some sense of the current documentation. Via "authorization" and the registry it seems easy enough to prevent a person (or in my case ALL people besides a set of a few defined annotators) from editing or deleting an annotation.

``` javascript
 var authorization = {
            //return a true or false here based on whatever...
            permits: function(){ return false;},
            //get a user id from my authorization schema blah blah
            authorizedUserId: function (u) { return '12345'; }
      };

      //register the authorization and the viewer doesn't show any editing ability
      app.registry.registerUtility(authorization, 'authorizationPolicy');
```

While this is workable, looking at the current code I see NOTHING which disables the ability to CREATE A NEW annotation.  Looking at the text selector, main ui widget and the adder, nothing seems to be checking authorization or options to determine if this is allowed.

I can appreciate the widget concept and having developers create their own viewers and editors. However, I really think things like whether something is read only should be easier to manage.  Why can't the authorizationPolicy be extended to the adder and creation process for example?  It's very disappointing and kind of careless in my opinion to have permitEdit and permitDelete functions which are easily configurable but then there is literally nothing for creation. This can be easily abstracted out as well.

**Comment by tilgovi** [comment]
If we decomposed the lifecycle a bit more so that `textSelected` (just an example name) was a hook that you could catch and cancel by returning a rejected `Promise`, would that work?

**Comment by tilgovi** [comment]
Right now you would have to stop using the `ui.main` and handle the `TextSelector` `onSelection` callback yourself, then wire up the rest of the UI yourself.

I'm thinking greater decomposition of the hooks might help provide the right extensibility points.

**Comment by martinkoslof** [comment]
Hi there! YES I think this would be great (consider that a +1 to your recommendation) :

"If we decomposed the lifecycle a bit more so that textSelected (just an example name) was a hook that you could catch and cancel by returning a rejected Promise, would that work?"

Right now I am using the registry and somewhat rolling my own hack.  I am using the start hook and basically injecting my own function using the result of a promise I pass into my constructing class, i.e.

``` javascript
this.app.registry.registerUtility({editable:function(){ return isEditable;}}, 'isReadOnly');
```

So in my hook I query this utility from the registry and if editable is false I use jquery to remove the adder.  It's not perfect, but I feel like the ui.main is a great baseline editor and if I had a custom UI or specific needs I completely agree we should roll our own, using the base widget class.  If we could get a hook into the text selection event and cancel the event that would be awesome.

Thanks for all the great work :)

**Comment by tilgovi** [comment]
Thanks for the information. I opened #583 to track this enhancement.

**Comment by kikito** [comment]
Hi there, we are using annotator beta and we "resolved" this particular issue with CSS. Like this:

```
<% unless user_signed_in? %>
<style> .annotator-adder { display: none; } </style>
<% end %>
```

Crude, but it works.

**Comment by agonbina** [comment]
For anyone else out there who is struggling to set it up, here is a module that you can include to your `App` instance which enables a read only mode:

``` js
  var viewerModeUi = function () {
    var element = document.body // Or whatever is your selector/element when you initialize the annotator
    var ui = {}

    return {
      start: function () {
        ui.highlighter = new annotator.ui.highlighter.Highlighter(element)
        ui.viewer = new annotator.ui.viewer.Viewer({
          permitEdit: function (ann) { return false },
          permitDelete: function (ann) { return false },
          autoViewHighlights: element
        })
        ui.viewer.attach()
      },
      destroy: function () {
          ui.highlighter.destroy()
          ui.viewer.destroy()
      },
      annotationsLoaded: function (anns) {
        ui.highlighter.drawAll(anns)
      }
    }
  }

  var app = new annotator.App()
  app
    // Other modules
    .include(viewerModeUi)
    .start()
```
