### ISSUE TITLE
How to customize the UI part of annotations in Annotator 2.0 

### ISSUE THREAD

**Issue by anandi2i** [openannotation/annotator#581]
Hi
    Currently iam using annotator 2.0 for my site development and i was pitty worrying about UI customization for annotations create, edit and delete . I need my own customization for those things and i want to externally call my API for storage also.
    I referred your documentation(http://docs.annotatorjs.org/en/latest/modules/ui.html)  -  ['annotator.ui.main' ] for UI customization, But couldn't find any example for own module development. 

  So my question is
   How to create my own module to achieve custom UI part in annotations with create, update, edit and delete ?
    It will be grateful for me if you explain with an example

**Comment by tilgovi** [comment]
Are you looking to add fields to the annotations or to completely change the UI of the pop-up in ways that go beyond CSS and added fields?

**Comment by anandi2i** [comment]
1. I want to change the UI part completely...As per documentation of annotator2.0 the package "app.include(annotator.ui.main)" gives the default template. I do not wish to include this and instead i need some my customized part like below 
   ![customized_ui](https://cloud.githubusercontent.com/assets/6039097/11494417/37207072-9828-11e5-97b6-5c4b9d081022.png)
2. I need something to create more annotations for the text in the popup itself. Currently it's not possible to add until we selecting the same text again.

meanwhile i need to pass my own user details too...

**Comment by anandi2i** [comment]
And what you mean by "The module provides just one possible configuration of the various components in the annotator.ui package, and users with more advanced needs may wish to create their own modules that use those components (which include TextSelector, Adder, Highlighter, Viewer, and Editor)." in the documentation

.....Is it possible to use these 5 components in my own module .....Could you please explain with an example ?

**Comment by tilgovi** [comment]
See the ui.main module code. Use it as a template for your own.

**Comment by anandi2i** [comment]
Ya...I got it..I have another question

How to include "Rich text"  plugin with annotator2.0

In annotator1.x ..we have something "add plugin" to add external editors

My ultimate aim is to integrate Tinymce plugin with annotator2. 0

**Comment by tilgovi** [comment]
You're looking for http://docs.annotatorjs.org/en/latest/modules/ui.html#viewer-editor-extensions

**Comment by bgarr** [comment]
Hi Anand,
Don't know if you are still working on a custom Annotator 2.x UI, but it's
something we've done, so this might be helpful:
http://inspect.georgetown.domains/uncategorized/customized-ui-for-annotator-2-0/

Best,
Bill Garr

**Comment by manojdarshana** [comment]
@tilgovi  Cant we change this UI change via a plugin ?

> See the ui.main module code. Use it as a template for your own. 

where you suggesting to change the annotatorjs library ?

**Comment by shardiwal** [comment]
I want to add few more items to adder, can you please guide, how can i do that ?

**Comment by tilgovi** [comment]
@manojdarshana No, I am suggesting to implement your own main UI, using the annotator library as a guide. The ui.main plugin is an example.

@shardiwal You should implement your own adder and use it in your own UI.

**Comment by shardiwal** [comment]
@manojdarshana Do you have any example on how can i implement my own adder and how to use that ?
