### ISSUE TITLE
How to annotate the contents of tinyMCE

### ISSUE THREAD

**Issue by anandi2i** [openannotation/annotator#586]
Hi Randall Leeds,
      Sorry for asking a question again because of not able to send mails to discussion forum. Please comment out the forum details...

Is it possible to create annotations in tinyMCE editor ?

I wish to annotate the contents of my tinyMCE editor and load the stored annotations also.

**Comment by tilgovi** [comment]
I am not familiar with tinyMCE internals. I do not know what an integration would look like.

I do not know what you mean about not being able to send emails. If you need help posting to the forum, feel free to email me directly.

**Comment by tilgovi** [comment]
Inside a WYSIWYG editor there is typically not a selection in the normal sense of a text selection in the browser. The editor usually handles displaying the cursor beam, handling mouse or keyboard events that move the cursor or create selections, and highlighting the current selection.

Since none of this is visible to annotator directly (often the mouse events won't even bubble out of the editor widget) adding annotator to an editor like TinyMCE requires that you integrate tightly with TinyMCE and Annotator to reflect activity between them.

This is outside the scope of Annotator proper, but if you attempt an integration and find that there are components of Annotator that are difficult or impossible to access at a low enough level for your integration, open specific issues about your needs.

**Comment by tilgovi** [comment]
You may want to look into the TinyMCE plugins, like the anchor plugin, and see if you can extend from there: https://www.tinymce.com/docs/plugins/anchor/

**Comment by anandi2i** [comment]
```
    Actually tinyMCE uses IFRAME to load its content...if annotator
```

will work for IFRAME contents in the sense , definitely it will be good to
proceed further....

On Sun, Dec 13, 2015 at 6:20 AM, Randall Leeds notifications@github.com
wrote:

> Inside a WYSIWYG editor there is typically not a selection in the normal
> sense of a text selection in the browser. The editor usually handles
> displaying the cursor beam, handling mouse or keyboard events that move the
> cursor or create selections, and highlighting the current selection.
> 
> Since none of this is visible to annotator directly (often the mouse
> events won't even bubble out of the editor widget) adding annotator to an
> editor like TinyMCE requires that you integrate tightly with TinyMCE and
> Annotator to reflect activity between them.
> 
> This is outside the scope of Annotator proper, but if you attempt an
> integration and find that there are components of Annotator that are
> difficult or impossible to access at a low enough level for your
> integration, open specific issues about your needs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openannotation/annotator/issues/586#issuecomment-164205168
> .

## 

Regards,
_Anand N G_
Software Engineer | E-mail: anand.n.g@ideas2it.com
http://projets.geekfg.net/res/mailto:mailto:balakrishnan.k@ideas2it.com |
Mob: 91-97151 40860 |
_Ideas2IT Technologies_
Radaptive http://www.radaptive.com/ | IdeaMed http://www.ideamed.in/ |
Bharatmoms http://www.bharatmoms.com/
5/32, 1st Cross Street(East), Shenoy Nagar, Chennai-600030
W : www.ideas2it.com | T : 91-44-4330005
_DISCLAIMER -_
This e-mail and any files transmitted with it are for the sole use of the
intended recipient(s) and may contain confidential and privileged
information. If you are not the intended recipient(s), please reply to the
sender and destroy all copies of the original message. Any review, use,
disclosure, dissemination, forwarding, printing or copying of this email,
and/or any action taken in reliance on the contents of this e-mail is
strictly prohibited and may be unlawful. Opinions, conclusions and other
information in this message that do not related to official business of the
company shall be understood to be neither given nor endorsed by Ideas2IT
Technologies. Any information contained in this email, when addressed to
Clients is subject to the terms and conditions in governing the client
contract.
