### ISSUE TITLE
Add with previous annotations 

### ISSUE THREAD

**Issue by maz1989** [openannotation/annotator#587]
How can I load my html page with previous annotations? 

For example I need annotation appear when I load the below page as:

![img](https://cloud.githubusercontent.com/assets/16080780/12020653/6480b3e6-ad87-11e5-8fdd-054764b99ed6.PNG)

**Comment by tilgovi** [comment]
Please see the documentation for the http storage module according to your version of Annotator.

1.2.x: http://docs.annotatorjs.org/en/v1.2.x/storage.html
2.0.x: http://docs.annotatorjs.org/en/latest/modules/storage.html

If you have a question about a specific issue you encounter, please let us know.

**Comment by maz1989** [comment]
I try to store annotations data in database and then when I reload the page I want to render the annotations from database 
please give me full code java script example how to re render annotation in the screen when I reload the page  

the ex in http://docs.annotatorjs.org/en/latest/modules/storage.html#storage-implementations 
unclear
