### ISSUE TITLE
Hi, will the annotator be supported annotation like word annotation?

### ISSUE THREAD

**Issue by fewiki** [openannotation/annotator#588]
Hi, will the delete and insert mark like word annotation be supported, thanks. Like the picture.

![image](https://cloud.githubusercontent.com/assets/13325335/12382967/288a47c6-bddb-11e5-9707-b53fa9c3ba39.png)

**Comment by tilgovi** [comment]
Unlikely. Annotator is moving toward providing only a core and leaving more of the user interface to the user. You could build an application using Annotator that does what you describe.
