### ISSUE TITLE
Show all comments at once?

### ISSUE THREAD

**Issue by jonahx** [openannotation/annotator#593]
I wasn't able to find the answer to this in the docs -- I apologize if it's there....

By default a comment creates a highlight over the text to which it applies -- and can subsequently be viewed by mousing over that highlight.

Is there a global toggle that makes all comments visible at once, without the need to mouseover them individually?

**Comment by tilgovi** [comment]
No, there is no such feature. Annotator is written to only have a single viewer widget with its content replaced to match the highlight where the mouse is positioned.

You are, of course, free to instantiate your own viewer widget and do handle your own user interface.
