### ISSUE TITLE
In some webpage, cannot working normally?

### ISSUE THREAD

**Issue by luboq** [openannotation/annotator#594]
In [this page](https://www.jetbrains.com/webstorm/help/quick-start-guide.html), call the bookmarklet will ruin the page.

and [this page](https://www.zhihu.com/question/20936155), call the bookmarklet has no response.

**Comment by bobchao** [comment]
If you are using a hosted script files (with the bookmarklet) on a https web page, Firefox will block it for security reason.

**Comment by luboq** [comment]
Thanks!
