### ISSUE TITLE
wanted: serverless operation

### ISSUE THREAD

**Issue by jason-s** [openannotation/annotator#596]
HTML isn't just webserver-based; we are using HTML to write documentation for some in-house software. Annotator sounds great but it requires a server to store and share the info.

Please please please facilitate a serverless operation to utilize local storage and exchange via email.

**Comment by tilgovi** [comment]
The built-in module provides HTTP-backed storage but there are community storage modules, too.

https://github.com/aron/annotator.offline.js

If you find it inadequate I encourage you to reach out to the author or to contribute your own and share a link with us, but as this does not constitute a bug in the core of Annotator I'm going to close this issue.

Thanks.
