### ISSUE TITLE
annotationsLoaded hook possibly firing prematurely

### ISSUE THREAD

**Issue by dalton** [openannotation/annotator#598]
*\* Annotator v2.0.0-alpha.3-6a22d86

I'm creating a module because I want to be able to associate groups of annotations by color, but it does not appear to be firing at the right time and is only affecting some of the annotations. The same annotations each time.

The module is simple enough so far. I want to change the highlight color if and after I hover over it.

`var belief = {};

belief.linkArguments = function (options) {
    options = options || {};

```
return {
    annotationsLoaded: function (annotations) {
        $(".annotator-hl").mouseover(function () {
            $(this).css("background-color", "pink");
        });
        $(".annotator-hl").mouseout(function () {
            $(this).css("background-color", "orange");
        });
    }
}
```

};
`

I then create the annotations app like so

```
var app = new annotator.App();
app.include(annotator.ui.main);
app.include(annotator.storage.http, {
  prefix: 'http://localhost:3000/beliefs',
  urls: {
    create: '/',
    update: '/{id}',
    destroy: '/{id}',
    search: '/' + gon.doc_id
  }
});
app.include(belief.linkArguments);
app
    .start()
    .then(function () {
      app.annotations.load();
    });
```

Now when I hover over some of the annotation-hl spans I get the color to change, but not all of them. I haven't figured out a common pattern just yet.

**Comment by tilgovi** [comment]
The highlighter listens to `annotationsLoaded` itself. You cannot rely on the order of hooks and so therefore you cannot rely on the highlights existing when the `annotationsLoaded` hook is running.

You should use event delegation on your container element rather than attaching the handler to every highlight individually, or use CSS hover states.

**Comment by tilgovi** [comment]
In other words, `annotationsLoaded` is fired when the annotation is loaded by the storage module, but is does not guarantee any UI state.
