### ISSUE TITLE
annotations replies

### ISSUE THREAD

**Issue by joshbrowninguk** [openannotation/annotator#599]
Hi,

I'm currently looking into implementing a reply feature to annotations, so a user can reply with a comment on an existing annotation.

I was wondering if there is any plans to add this to annotator in the future? or if anyone has had any experience with adding this?

**Comment by tilgovi** [comment]
Unlikely to be added to the core right now.

I have written reply functionality before by storing annotations that contain a thread field much like email message id and in-reply-to headers.

Annotator has been moving away from dictating the particular fields and shape of the annotations to focus on interactions and hooks only. The default UI makes its own assumptions about certain fields. You are free to add whatever extensions you like and store that data however you see fit.

If someone does modify the built in UI to cleanly support replying and is willing to document and test it, I would help them get it merged, but there is no particular plan to add this feature.
