### ISSUE TITLE
Version 2 mobile friendly?

### ISSUE THREAD

**Issue by snsxn** [openannotation/annotator#603]
I'm trying without results to make it work in mobile but when I select a word it appears the default mobile behavior. Any guidelines to start?

**Comment by tilgovi** [comment]
I'm not aware of any such guidelines. If you develop a mobile application using Annotator I encourage you to share improvements and issues. The goal of 2.0 is to clarify the bounds of the Annotator core and define its extension interface more clearly. A mobile-friendly UI can be implemented on top of that.
