### ISSUE TITLE
How to add buttons once you highlight text

### ISSUE THREAD

**Issue by ajoys** [openannotation/annotator#604]
I want to customize the buttons that popup once text is highlighted. How do I go about doing that? I tried looking at the docs and wasn't able to find a solution.

**Comment by tilgovi** [comment]
There is not a straightforward way to do this right now.

**Comment by ajoys** [comment]
Any way would be helpful. Can you provide some sort of resource I can refer to?

**Comment by tilgovi** [comment]
Is this v1.2.x or master?

**Comment by ajoys** [comment]
Currently using 1.2.10, however I am willing to switch to master if it makes the problem easier to solve.

**Comment by sanchitgera** [comment]
+1

**Comment by tilgovi** [comment]
It should be possible to subclass `Annotator` and override the `adder` key in the `html` property: https://github.com/openannotation/annotator/blob/v1.2.x/src/annotator.coffee#L18
