### ISSUE TITLE
Problems showing annotations after saving and reloading a page.

### ISSUE THREAD

**Issue by ajoys** [openannotation/annotator#606]
Hello,

I currently save any annotations made on my webpage to my database using the Store plugin, and it seems to get retrieved on page reload, however the annotations are not shown on the webpage. Is there something specific I need to do in order for the annotations to show up again?

Currently my data coming back is formatted as follows:

```
{
'total': 1,
'rows': {
     'range': {}
      }
}
```

**Comment by jhou2** [comment]
You might need to load the annotations.  Something like:
var annotations = [Array of your stored annotations];
var ann = $(element).annotator();
ann.annotator("loadAnnotations", annotations);

**Comment by ajoys** [comment]
The annotations are being loaded. The issue is that the document which is being annotated is not loaded before the annotations are. Is there a way to defer the annotation till the document is loaded?

**Comment by ajoys** [comment]
FIXED: I just waited for my document to load, and only after that loaded the annotation.

**Comment by tilgovi** [comment]
Great!
