### ISSUE TITLE
Adder button rendered offscreen

### ISSUE THREAD

**Issue by melat0nin** [openannotation/annotator#611]
Hello all

I'm trying to implement v1.2.7 (full) but the adder is rendered offscreen by some margin. It's been added to a bootstrap page which is quite long (body height of 2800px) and this happens in FF47 and Chrome 51. No other js errors and I can't identify any conflicts with other CSS.

Any pointers much appreciated :)
![capture](https://cloud.githubusercontent.com/assets/912688/15155369/15081ee6-16da-11e6-8e2f-aff1406b4369.PNG)

**Comment by tilgovi** [comment]
@melat0nin did you solve your issue?

**Comment by melat0nin** [comment]
Yes I upgraded the library to 1.2.10 and it disappeared. I had been using
1.2.7.

. . . . .
