### ISSUE TITLE
Annotations Not Being Stored With Associated User

### ISSUE THREAD

**Issue by kferencz91** [openannotation/annotator#613]
I am using Annotate 1.2 with AnnotateIt storage. I have generated a token with consumerKey (from my account), userId, issuedAt, and ttl, as well as the secret, and verified it against jwt.io to make sure it is returning the correct data. This token is then provided in the token area for the Auth plugin. Code below:

`var content = $('body').annotator();

```
content.annotator('addPlugin', 'Auth', {
  tokenUrl: '/auth/token',
  token: 'TOKENREMOVED',
  autoFetch: true
});

content.annotator('addPlugin', 'Store', {
  prefix: 'http://annotateit.org/api',
});

content.annotator('addPlugin', 'Permissions', {
    user: 'kferencz',
    permissions: {
      'read':   [],
      'update': [],
      'delete': [],
      'admin':  []
    }
});`
```

When I do this, the annotations "stick" and if I reload the page, I can see the annotations with the username "kferencz" attached. I can continue to make updates and add new annotations.

However, if I log into my kferencz account, or I try to query that username through the API, no results show up/there are no annotations. What would be causing this? The annotations have to be stored somewhere for them to be "sticking" and showing up for others accessing the site, so I'm confused as to what is going on here. Any help??

I changed the token to "testtesttest" just to make sure the token is being utilized as it should be, and sure enough, if I change the token to the above, it allows me to make annotations, but not "save" them - ie, nothing appears on a reload of the page. However, if I change it back to what my token was previously, it allows me to make annotations and they appear on a refresh (or for anyone else viewing the site).

I was trying to debug the annotations, but couldn't figure out how to print the raw annotations in my console either. Any help would be appreciated. I would like to, down the line, be able to query all annotations by kferencz and display them, so I'm not sure what step is being missed here.

**Comment by kferencz91** [comment]
Want to update that if I follow the "link" to any of the annotations (that appears in the right corner of the annotation itself on the website), I receive a 401: Not Authorized error, even if I am logged in as kferencz. An example of one of those annotation links is: http://annotateit.org/annotations/AVTAML5ei7V2MzlsGTj9

**Comment by tilgovi** [comment]
If you don't specify a user in the Permissions plugin, the Auth plugin should fill it in from the token. Try loading the Permissions plugin before the Auth plugin to be sure there's no race there. Then, try not specifying the token. AnnotateIt will generate the token for you based on your cookie session if you're logged in at AnnotateIt.

If none of this works I can try to dig in and help debug a bit more.

**Comment by kferencz91** [comment]
I completely removed the Permissions plugin just to see if that would help (it removed some of the options within the annotation itself, but didn't seem to change the storage portion). Still not working. 

Due to our intended functionality for the site, we do not want to use anyone else's login information for these annotations - we want them all stored in our one user account with everyone able to make annotations without having to login to the AnnotateIt service. Therefore, I will have to include a token :-/ 

As I said, it is odd to me that I can refresh the page and still see the annotations. They must be saved "somewhere" - the question is, where?? (Or what bug is happening to cause this 'middle' functionality, so to speak).

**Comment by tilgovi** [comment]
Yes, I understand what you want to do. I am trying to help narrow down the cause.

Please try loading the permissions plugin first, with default options and no user set, then the author plugin without a token.

If that's working, I'll help you figure out how to get the behavior you want.

**Comment by tilgovi** [comment]
Ah, I think I might understand your problem.

When you use a token of your own creation, using your consumer key, these annotations are associated with the consumer key and kept apart from other annotations in the API. This means that as an application developer you are free to associate any username with these annotations, not just the username of the account that owns the token. If you query the public API endpoint without a token, you will not see these annotations. Even though the permissions state that they are public, they are only public to your application and tokens it has created.

If you create a token and specify it in X-Annotator-Auth-Token header you should be able to query the API for it.

**Comment by kferencz91** [comment]
Aha! Ok, that makes sense that you need to pass the token in the header if you're trying to query outside of it. I was very confused as to how they were being "saved" if they weren't going anywhere!!! :) But clearly they were, just need some extra security there. I don't have time right this second to test it out, but what you're saying makes total sense, so I will mark this closed. Thanks for your help!

**Comment by tilgovi** [comment]
You're welcome! Sorry for the confusion.
