### ISSUE TITLE
Uncaught ReferenceError: annotator is not defined

### ISSUE THREAD

**Issue by webmagnets** [openannotation/annotator#615]
I am using the latest jquery (https://code.jquery.com/jquery-2.2.3.min.js) and the latest stable release.

I'm getting this error on page load: Uncaught ReferenceError: annotator is not defined

Any ideas? Possibly you need more information before you can answer.

**Comment by tilgovi** [comment]
Can you show how your include Annotator and how you instantiate it?

**Comment by webmagnets** [comment]
Sure. Thanks for the help.
...
    <script src="//code.jquery.com/jquery-2.2.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.4.0.min.js"></script>

```
<script src='js/annotator-full.min.js'></script>
<script src='js/annotator.touch.min.js'></script>

<link rel="stylesheet" type="text/css" href="css/tooltipster.css" />
<script type="text/javascript" src="js/jquery.tooltipster.min.js"></script>

<link href='css/annotator.min.css'>
<link href='css/annotator.touch.css'>
</head>
```

...

```
     <script>
    var app = new annotator.App();
    app.include(annotator.ui.main);
    app.include(annotator.storage.http);
    app
        .start()
        .then(function () {
        app.annotations.load();
        });
</script>
</body>
```

**Comment by tilgovi** [comment]
It looks like you may be using Annotator v1.2.x while following usage documentation for the master branch.

**Comment by webmagnets** [comment]
I got that code directly from annotatorjs.org's home page. Is that project out of date?

**Comment by tilgovi** [comment]
The home page shows working code, although I realize now that the "usage" link goes to the latest version of the documentation, which is alpha code for future release. Apologies if that led you astray. The docs link in the header goes to the v1.2.x documentation.

**Comment by tilgovi** [comment]
Sorry for the delay in responding.

**Comment by shaunswanson** [comment]
This problem still exists, I was confused until I saw this thread (the linked documentation is incorrect from the homepage of the project).

**Comment by krisnaw** [comment]
Solved, using the right documentation
