### ISSUE TITLE
Problem when annoting part in a HTML tag

### ISSUE THREAD

**Issue by JeremyFERNANDES** [openannotation/annotator#616]
If i highlight a part of my HTML page in a HTML tag when i start my comment on the first character of the tag, the annotation popup doesn't always display.

Example : HTML : `<em>annotatorJs </em>`; Highlighted : anno

Code version : 1.2.10

Thank you

[index.zip](https://github.com/openannotation/annotator/files/285964/index.zip)
-> i create an annotator on the id comment

**Comment by tilgovi** [comment]
I am sorry, but I do not understand your issue. Can you maybe share an example and describe the selection you make that fails?

**Comment by JeremyFERNANDES** [comment]
I have updated my first comment.

**Comment by tilgovi** [comment]
I can't reproduce this, at least not reliably. If you can provide a simple, reproducibly test case that shows all your code and doesn't require me to use PHP I can try to debug.
