### ISSUE TITLE
Disable comment popup

### ISSUE THREAD

**Issue by sarfraznawaz2005** [openannotation/annotator#621]
Hello,

It it possible to disable comment popup? In other words, is it possible to just highlight the selected text without necessarily adding a comment ?

I searched documentation but could not find a way to disable it.

Thanks

**Comment by tilgovi** [comment]
There is no immediately supported way to do this, but you could override methods of the Annotator to change this code: https://github.com/openannotation/annotator/blob/v1.2.x/src/annotator.coffee#L578

**Comment by tilgovi** [comment]
As this is a support question and not an issue report, I'm going to close this. More recent and future development for Annotator considers the lack of configuration for what happens after selection an area in need of development. See issues like #583 and #584.

**Comment by sarfraznawaz2005** [comment]
okay got it, thanks
