### ISSUE TITLE
Stackoverflow question with bounty

### ISSUE THREAD

**Issue by webmagnets** [openannotation/annotator#622]
http://stackoverflow.com/questions/37956213/how-can-i-stop-my-page-from-scrolling-when-i-annotate-on-a-touch-device

**Comment by tilgovi** [comment]
Please don't cross-post support questions from StackOverflow. There is also an IRC channel and a mailing list where you can engage community support if you need to draw more visibility to a question like that. I'll offer some suggested avenues over on StackOverflow, though.
