### ISSUE TITLE
Annotator controls for edit/delete not working

### ISSUE THREAD

**Issue by wgroenewold** [openannotation/annotator#631]
Hi,

I'm currently working on a Wordpress-based backend for Annotator. I'm working with the 1.2.x branch. I already managed to create and retrieve posts, but somehow updating and deleting won't work. I already worked out adding the user to the post, but somehow the buttons on the annotation-bubble for edit and delete won't trigger anything.

**Comment by CNDLS** [comment]
Hello Wouter,
I'm not a maintainer of the annotator code, but I'm working with a fork of v 2.x that we are using at Georgetown University. I'm interested in making a WordPress plugin for it, too.

What are you seeing in the browser console? Version 1.2x calls onEditAnnotation() and onDeleteAnnotation() methods of the Annotator object when the buttons are clicked. You could put debugger statements in those methods to see if they are getting called.

Good luck!
Bill Garr

**Comment by wgroenewold** [comment]
Hi Bill,

I will share my code when it's working so you can port it to v2.x. I don't even get an click event on the buttons on the moment (not even a hover state), so I must be doing something really wrong. I just included the http://assets.annotateit.org/annotator/v1.2.10/annotator-full.min.js on the page and used the following code:

```
var content = $('.content').annotator({
            readOnly: false
        }
    );

var annotator = $('.content').annotator().data('annotator');
    annotator.addPlugin('Permissions', {
        user: 'Wouter',
    });

content.annotator('addPlugin', 'Store', {
        prefix: annotate.base + '/wp-admin/admin-ajax.php',
        emulateHTTP: true, //because WP doesn't support PUT and DELETE on ajax
        urls: {
            create: '?action=annotate_create&postid='+annotate.postid,
            read: '?action=annotate_read&id=:id',             
            update: '?action=annotate_update&id=:id'+'&nonce='+annotate.nonce,
            destroy: '?action=annotate_destroy&id=:id',
            search: '?action=annotate_search&postid='+annotate.postid
        },

        loadFromSearch: {
            'limit': 0,
            'all_fields': 1
        },

        showViewPermissionsCheckbox: false,
        showEditPermissionsCheckbox: false
    });
```

**Comment by wgroenewold** [comment]
In case somebody reads this. Defining the z-index to 999 for the buttons fixed it...
