### ISSUE TITLE
Annotations only showing intermittently using Annotateit.org

### ISSUE THREAD

**Issue by cwbuecheler** [openannotation/annotator#632]
Hi guys,

I've been working to get annotator 1.2.10 up and running locally, to perform some tests. I wanted to save annotations to annotateit.org, and have set up an account there. I built out a JWT generator and set up my annotator like this:

``` javascript
$(document).ready(function() {

  var content = $('#content');

  content.annotator('setupPlugins');
  content.annotator('addPlugin', 'Auth', {
    tokenUrl: '/jwt',
  });

  content.annotator('addPlugin', 'Store', {
    // The endpoint of the store on your server.
    prefix: 'http://annotateit.org/api',

      // Attach the uri of the current page to all annotations to allow search.
      annotationData: {
        'uri': 'cwbtesturi'
      },

    // This will perform a "search" action when the plugin loads. Will
    // request the last 20 annotations for the current url.
    // eg. /store/endpoint/search?limit=20&uri=http://this/document/only
    loadFromSearch: {
      'limit': 20,
      'uri': 'cwbtesturi',
    }
  });

});
```

Note: I think it's possibly weird to do `setupPlugins` and then immediately `addPlugin` on two default plugins ... but it's the only way I could get `/jwt` to be queried. The good news is: it works -- I can save annotations to the server, and it correctly stores them. The bad news is: it only retrieves them about one in every ten or fifteen page refreshes. The rest of the time, it sends back the following:

``` json
{
  "total": 0, 
  "rows": []
}
```

I've checked the request headers and they're identical every time. The only thing that changes is the token, which leads me to think either:

a) my token generation is only intermittently working ... except this doesn't seem to be the case, since saving annotations always returns a 200, so it seems like all the tokens are good.

b) there's some kind of race condition happening somewhere ... except that doesn't make sense, since the token is always being sent in the `x-annotator-auth-token` header.

c) something's borked somewhere in the process that's not under my control

Here is my token generation, using [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken):

``` javascript
  var normalDate = new Date();
  var isoDate = normalDate.toISOString();
  // sign with default (HMAC SHA256)
  var token = jwt.sign({
    consumerKey: 'MYCONSUMERKEY',
    userId: 'cwbuecheler',
    ttl: 86400,
    issuedAt: isoDate,
  }, 'MYSECRETKEY');
```

Any suggestions?

**Comment by tilgovi** [comment]
You can pass it options to `setupPlugins`.

``` js
content.annotator('setupPlugins', {
  Auth: {
    tokenUrl: '/jwt'
  }
});
```

It may in fact be a race condition where the `setupPlugins` call loads the `Auth` plugin and it immediately makes a request to get a token from annotateit. I actually think that you're not allowed to load plugins twice and it should be generating a console message telling you so.

**Comment by cwbuecheler** [comment]
Thanks for the info! I don't think I'm getting a console error, but I'll look into doing the setup just with `setupPlugins` rather than the way I'm doing it now, and see if that fixes the issue.

**Comment by cwbuecheler** [comment]
New code, same issue. I got rid of setupPlugins because I really only want auth/store, and am just using addPlugin instead.

Annotations save correctly but only show up once every ten page refreshes or so. I'm pretty sure it's not a race condition at this point, as only one XHR GET call is being made to annotateit.org -- could something be wrong with the server over there? It's also weird because the "my account" page on annotateit.org says I've made zero annotations, but they're definitely being saved to the server.

``` javascript
var content = $('#content').annotator();
content.annotator('addPlugin', 'Auth', {
  tokenUrl: '/jwt',
});
content.annotator('addPlugin', 'Store', {
  prefix: 'http://annotateit.org/api',
  annotationData: {
    'uri': 'cwbtesturi',
  },
  loadFromSearch: {
    'limit': 20,
    'uri': 'cwbtesturi',
  }
});
```

Appreciate any other thoughts or advice. Thanks!

**Comment by tilgovi** [comment]
I'm not surprised that you see no annotations when you log in at annotatetit.org. That's probably expected.

When you issue your own tokens using your consumer id you are creating all the annotations in a sort of sandboxed space. Through this behavior, you're given the freedom to assign whatever user identifiers you like for the tokens you create without worrying about name collisions. When you log into annotateit.org, you are using the annotateit.org consumer and seeing your personal annotations.

It's possible something is wrong with the server over there. There have been reports of intermittent 500s for a long time now. Mandrill shut down and no one ever changed the mail server (so email confirmation or lost password features, if there are any, are probably not working). No one is maintaining it for a couple years now.

**Comment by cwbuecheler** [comment]
Ah, ok, thanks. That's good to know. We're building our own store anyway -- the plan was just to offer something else as a potential alternative. A site that hasn't been maintained in two years is probably not the best option, there, so I'll seek something else out.

Oh, and the sandboxes space concept makes sense. Thanks for the explanation.

Guess I'm all good! Far as I'm concerned, this is a closed issue.
