### ISSUE TITLE
Is it possible to access the main() local state (s) variable?

### ISSUE THREAD

**Issue by alukach** [openannotation/annotator#633]
I am working through a bug on a plugin (emory-lits-labs/annotator-imgselect#3). The background of the bug is that after editing an annotation, any new annotations open the Editor in the position of the last-edited annotation (rather than position of the newly created annotation). I believe the cause of the bug is that [the `interactionPoint` property of the local state object defined within `main()`](https://github.com/openannotation/annotator/blob/5ef5edf157fe728b2d6d95d01e26a55c508c0c44/src/ui/main.js#L221-L223) is not correctly set after editing an annotation (oddly, only when using the plugin).

I can see that the [text selector updates the interaction point](https://github.com/openannotation/annotator/blob/5ef5edf157fe728b2d6d95d01e26a55c508c0c44/src/ui/main.js#L249) but this is only possible because the modification is defined within a function declared within `main()`. 

My questions:
- Is it possible for a plugin to modify the `interactionPoint` defined in `main()`?
- Am I barking up the wrong tree? Is there something that I'm obviously missing that causes the interaction point to be incorrect? Being that this bug only occurs when using the annotator-imgselect plugin, I'm led to believe that the plugin is doing something wrong. Perhaps there's a function that should be run after a tag is edited? If you're curious, the plugin can be found [here](https://github.com/emory-lits-labs/annotator-imgselect/blob/develop/src/annotator.imgselect.js).

**Comment by tilgovi** [comment]
The only thing I can think of is that I see all your hooks are returning `true`. Some of those, like `annotationCreated` should be returning either the annotation or a `Promise` of that annotation. Maybe something like this is breaking functionality in the UI core.

The local state where `interactionPoint` is stored is deliberately local state, though. We were trying to get more careful and specific about what is public (supported, maintained interface) and what is private data.

**Comment by tilgovi** [comment]
The intended way to do this is to not use the `ui.main` plugin. Use that code as a boilerplate and create your own UI that loads and manages the interactions between the components of your application.

**Comment by alukach** [comment]
> The intended way to do this is to not use the ui.main plugin. Use that code as a boilerplate and create your own UI that loads and manages the interactions between the components of your application.

I'm not entirely sure what you mean by this. [Is this](https://github.com/emory-lits-labs/annotator-imgselect/blob/develop/demo/index.html#L82) what you're referring to IRT "using the `ui.main` plugin"?  Can you direct me to an example of someone doing it the more-correct way?

**Comment by tilgovi** [comment]
What I mean is that you can copy the code from the main UI plugin [1] and modify it to suit your needs. Then you include that _instead of_ `ui.main`.

[1] https://github.com/openannotation/annotator/blob/master/src/ui/main.js

**Comment by Nicolabo** [comment]
@alukach Hi, Did you solve this problem somehow?

**Comment by alukach** [comment]
@Nicolabo Nope, I didn't love the idea of duplicating `ui.main` in my codebase. The problem wasn't so huge that I couldn't live without fixing it.

Can you share your related issues? Maybe it will help shed light on what's going wrong.

**Comment by Nicolabo** [comment]
@alukach Yeah, I think that the problem is not related only to comment edition. It's about comment creation in text in general vs. comment creation on the picture. When you create a comment in the text or even, if you just highlight a text (but not clicking on adder), and then, try to create a comment on the picture, it will use previous comment's coordinates.
