### ISSUE TITLE
How to change the ui

### ISSUE THREAD

**Issue by manojdarshana** [openannotation/annotator#643]
Hi,
I am trying to change the Editor UI of this library. What is the best way to do this. Can i create a plugin via annotator-2.0.0-alpha.3 to achieve this? 
I am trying to build something like bellow. Adding 3 tabs using bootstrap. And add some dynamic content in each tabs.
![dad1](https://cloud.githubusercontent.com/assets/9097699/19270810/7a64a52e-8fdf-11e6-83fb-69012e8e9e28.png)

Any tips ? Tutorials ?

**Comment by skysoga** [comment]
Has this problem been solved?

**Comment by manojdarshana** [comment]
Nop. still waiting for a answer.

**Comment by manoj-mass** [comment]
Was able to solve this by going through the ui.main module and implementing something similar.

**Comment by tilgovi** [comment]
@manoj-mass is correct. `ui.main` is an example from which to create your own user interface.
