### ISSUE TITLE
Making Annnotator reload annotations

### ISSUE THREAD

**Issue by goudreinette** [openannotation/annotator#647]
Hi, 

My team is using AnnotatorJS together with ePub.js.
We are building a single-page application with Vue and Vuex (Flux architecture), and we're storing our annotations externally  from AnnotatorJS.
AnnotatorJS queries our annotation store on page load.
Because other components in our frontend use the same store to display and modify annotations, AnnotatorJS gets out of sync.

My question: Is it possible to have AnnotatorJS reload it''s annotations on command?

Storage module:

```javascript
export default function bukuAnnotator (section) {
    return {
        start() {
            dispatch('fetchAnnotations', window.uuid)
        },

        create(annotation) {
            dispatch('createAnnotation', {
                annotation: _.clone(annotation),
                section: section.idref,
                index: section.index
            })
            return annotation;
        },

        update(annotation) {
            dispatch('updateAnnotation', annotation)
            return annotation;
        },

        delete(annotation) {
            dispatch('deleteAnnotation', annotation)
            return annotation;
        },

        query() {
            if (state.annotations.annotations.length)
                return packAnnotations(annotationsForSection(section.idref))
            else
                return dispatch('fetchAnnotations').then(() =>
                    packAnnotations(annotationsForSection(section.idref))
                )
        },

        configure(registry){
            registry.registerUtility(this, 'storage')
        }
    }
}
```

**Comment by Poornima1110** [comment]
hey there ,
will this code help to  reload the annotation ?
Thanks

**Comment by goudreinette** [comment]
Hi,

We ended up building a custom solution.
AnnotatorJS' was just too limited for our purpose.

**Comment by Poornima1110** [comment]
hello ,
I just want that my annotation comment would be visible after reloading also . will it be possible ?
Thanks

**Comment by goudreinette** [comment]
Storage is explained here:
http://docs.annotatorjs.org/en/v1.2.x/storage.html#core-storage-api

**Comment by jwgmeligmeyling** [comment]
I also needed to refresh annotations in a way. In my situation there were annotations in the store for parts of the DOM that were still unrendered. 

I found a way how to do this in 1.2.x: `annotator.loadAnnotations(annotator.plugins.Store.annotations.slice())`.

However, there are two important issues. For one, annotations that were already rendered, were now rendered twice. Another issue was that for previously unrendered annotations, the annotations ranges were removed (because they could not be found in the DOM during normalization). I have found the following patches to resolve those two issues:

```diff
diff --git a/src/annotator.coffee b/src/annotator.coffee
index 766d4cb..a23df4f 100644
--- a/src/annotator.coffee
+++ b/src/annotator.coffee
@@ -294,6 +294,9 @@ class Annotator extends Delegator
     root = @wrapper[0]
     annotation.ranges or= @selectedRanges

+    if annotation.highlights
+      return
+
     normedRanges = []
     for r in annotation.ranges
       try
@@ -301,6 +304,8 @@ class Annotator extends Delegator
       catch e
         if e instanceof Range.RangeError
           this.publish('rangeNormalizeFail', [annotation, r, e])
+          # Don't mess up annotations that could not be loaded
+          return
         else
           # Oh Javascript, why you so crap? This will lose the traceback.
           throw e
```
