### ISSUE TITLE
1.2.10 isn't available versions with bower

### ISSUE THREAD

**Issue by chrispcb** [openannotation/annotator#654]
Hello,

Available version in https://github.com/ikr/annotator-bower.git: 1.2.9, 1.2.7, 1.2.6

**Comment by julianpoy** [comment]
That repository is not an official repository.

There are many other places to get it, including hosting your own. I suggest you use "annotatorjs", hosted here: https://github.com/critiqueit/annotator-bower

```
bower install --save annotatorjs
```

**Comment by chrispcb** [comment]
Ok thanks !
