### ISSUE TITLE
Error: You cannot have more than one instance of any plugin

### ISSUE THREAD

**Issue by achasapi** [openannotation/annotator#659]
I am trying to implement Annotatorj on the transcriptions of our [manuscript viewer website](http://humarec-viewer.vital-it.ch/). I would like to be able to associate the URI of the specific manuscript page for each annotation. I tried doing sth like this:
```
$(window).on('hashchange', function(e){
     var content = $('#text_elem').annotator();
     content.annotator('addPlugin', 'Store', {
          prefix: 'our/store/endpoint',
          annotationData: {
               'uri': window.location.href
          },
          loadFromSearch: {
               'limit': 20,
               'uri': window.location.href
          }
});
```
but I get an error saying I cannot have more than one instances of any plugin. Is it possible to alter the plugin on href change? I am looking for something like `content.annotator('modifyPlugin','Store')`. If not, any other ideas how to implement annotations with different URIs? 

Thank you!!

**Comment by achasapi** [comment]
I managed to find the solution for this. Here it is, in case it helps anyone with similar problem.

In annotator-full.js I modified the method `d.prototype._dataFor` as follows:
```
d.prototype._dataFor = function (b) {
            var c, d;
            var uri = {uri: this.element.context.baseURI}
            return d = b.highlights, delete b.highlights, a.extend(b, uri), c = JSON.stringify(b), d && (b.highlights = d), c
           // return d = b.highlights, delete b.highlights, a.extend(b, this.options.annotationData), c = JSON.stringify(b), d && (b.highlights = d), c
        }
```
This overwrites the URI provided in the annotationData variable with the path of the actual URL the annotation is made on.

**Comment by tilgovi** [comment]
How are you instantiating the annotator? Do you use `setupPlugins`? If so, you can pass the store config in as options to that method.
