### ISSUE TITLE
Standalone application/Desktop-based version?

### ISSUE THREAD

**Issue by baimafeima** [openannotation/annotator#673]
Are there any plans to have a desktop-based (not browser-based) version? I really like the annotation tools and would like to be able to work on documents locally at my computer. Alternatively, is it possible to integrate some of your technology into applications such as Bookworm? See this issue here: babluboy/bookworm#109
If there are no plans to offer a desktop-based version, could you point me to other desktop-based software with similar annotation capabilities?

**Comment by tilgovi** [comment]
There are no such plans. I don't know any desktop-based software for this. The bookworm developers are free to integrate this code in their application, as it's licensed very permissively.
