### ISSUE TITLE
How to annotate non-contiguous portions of text

### ISSUE THREAD

**Issue by pankus** [openannotation/annotator#674]
Is it possible to annotate non-contiguous portions of a text?
For instance, given the text:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit ...

I would like to simultaneously annotate "`Lorem`" and "`elit`" (the first and the last word), but not all the the words in between. I tried with the ctrl keyword, but it seems that it does not work.

**Comment by tilgovi** [comment]
As far as I know, Firefox is the only browser that supports multiple selections, but if the browser supports it I think Annotator does, too.

**Comment by tilgovi** [comment]
I just tested this on the annotatorjs.org site and it worked.

**Comment by pankus** [comment]
Is there any news about Annotator 2.3?
I'm very interested in the replacement of XPath-based selector code with Rangy. As far as I know, it allows the selection of non-contiguous portions of text, even in non-Firefox based browsers.
Many thanks in advance
