### ISSUE TITLE
Adding categories to annotatorJS

### ISSUE THREAD

**Issue by sonysujatha** [openannotation/annotator#685]
We wanted to add categories to  annotated text , were trying to find plugins to do that
http://annotatorjs.org/plugins/index.html

The few plugins in here 
Categories Plugin - Page Not found
Annotator-Categories - https://github.com/PoeticMediaLab/Annotator-Categories(unable to use it since its in coffescript)

Are there any plugins which we can use to categrize the annotation created. Would be really helpful if we can get a working example?

**Comment by tilgovi** [comment]
I do not know the status of any plugins that do this. If you create one, please share your experience.

**Comment by jamiefolsom** [comment]
Hi @tilgovi! @stephskardal wrote a categories plugin for Annotation Studio (which depends on annotator), but we haven’t extracted it from the project repo. I’ll post some links to the related front end and back end code.

**Comment by Nirvanatin** [comment]
@jamiefolsom  Could you provide the related codes?
