### ISSUE TITLE
build annotator on Windows

### ISSUE THREAD

**Issue by cwlinghk** [openannotation/annotator#687]
I downloaded and unzipped the v1.2.x to my disk. And then I use cmd and cd to the pkg folder. I try to run "make", but it gave me the error that
make i info INvoking all target
make i info Invoking annotator target
make x ERR not found: make-annotator.min.js

any ideas? Thank you very much.

**Comment by tilgovi** [comment]
No ideas. You can download a pre-built 1.2.10 from the releases page: https://github.com/openannotation/annotator/releases

v1.2.x has not been updated or maintained for some time and I have no plans to support it at all. I have very little time for any v2 work, either, but welcome PRs.
