### ISSUE TITLE
Annotation for single page appearing in multiple pages

### ISSUE THREAD

**Issue by timClicks** [openannotation/annotator#69]
I am having issues with annotations appearing on multiple pages of my site. That is, anything matching the XPath `/div/div` is being triggered in pages where the annotations are not made.

As a diagnosis, it looks like the annotation format doesn't contain a reference to the original URL. Additionally, my DOM contains elements with unique ids, which could be used to prevent this kind of thing happening.

Potential fixes:
- send a URI with each annotation so they're page-specific
- include ID/class/other attributes in XPath selectors so they're more specific

**Comment by oxhey** [comment]
@timClicks How did you solve this . Could you post the code?
