### ISSUE TITLE
I need clarity on the below items

### ISSUE THREAD

**Issue by kinnaree11** [openannotation/annotator#696]
We are looking for a javascript library that allows us to annotate on the tool we are building. The tool will have grids, graphs, and text. I have the following questions:

- Does it display the name of the user annotation
- Does it display history
- Does it scale? In other words, if I decrease/increase the size of my window does the annotation scale accordingly?
- I believe it is an open source
- Where do you store the data?
- Does it have the capability to be turned on/off? In other words, if some users do not want to use that feature can it be turned off?
- Is it an active library?
- Is it compatible with react?
- Is it hosted on cloud?

**Comment by tilgovi** [comment]
> Does it display the name of the user annotation

Yes.

> Does it display history

No.

> Does it scale? In other words, if I decrease/increase the size of my window does the annotation scale accordingly?

I'm not sure. The annotation pop-over has a default size, but it can be resized by dragging the corner.

>  I believe it is an open source.

Yes. MIT or GPL.

> Where do you store the data?

Wherever you want.

>  Does it have the capability to be turned on/off? In other words, if some users do not want to use that feature can it be turned off?

Yes.

>  Is it an active library?

No.

>  Is it compatible with react?

No built-in integration with React, but it could work with React.

> Is it hosted on cloud?

No. It's hosted where you host it.

**Comment by kinnaree11** [comment]
Does it support storing in database?
Also if user a annotates and then if user b provides comments than you will
not be able to see it? Is that what you mean by it doesn't display history!

**Comment by tilgovi** [comment]
These are all customization options. You will have to read the documentation for the storage and permissions plugins.
