### ISSUE TITLE
How can I load manual annotations?

### ISSUE THREAD

**Issue by tugcanolgun** [openannotation/annotator#698]
I would like to know how to load annotations manually. I am guessing either I have to feed a funtion with /search type object {'total':1, rows:[]} or the annotation object itself. 

I would appreciate if you could help.

**Comment by tilgovi** [comment]
What version?

**Comment by tugcanolgun** [comment]
2.x version. I know I need to write a StorageAdapter but I dont know how. Can you give me a one very simple example how to bind store and runHook?

**Comment by tilgovi** [comment]
How do you create the annotator? If you are using the stock UI, you can call `annotationsLoaded` with your annotations.

**Comment by tugcanolgun** [comment]
I managed to do what I wanted with creating a server instead. In the end it worked. Thank you for the help.
