### ISSUE TITLE
Enhancement: Add support for optional tags auto-complete in the tags plugin

### ISSUE THREAD

**Issue by pombredanne** [openannotation/annotator#92]
It would be great to have the option to get tag autocompletion support . There are jquery ui and jquery plugins for this alright... yet this could be part of the standard tag plugins (and configured optionally with options)
The source of autocompletion list could be so varied so this is likely best as open to the user to provide.

**Comment by anjesh** [comment]
Just wondering if it is possible to use select2 https://select2.github.io/examples.html instead of jquery ui autocomplete for the tags.

**Comment by tilgovi** [comment]
Probably. If it's not, let us know what we can do to make that possible.

**Comment by anjesh** [comment]
I managed to make this work, however i copied the tag plugin from the annotatorjs and created new tags plugin to use select2. Not a good hack, but it works :) https://github.com/anjesh/annotatorjs-hacks/blob/master/lib/annotator.plugin.tags.js
here's the demo https://rawgit.com/anjesh/annotatorjs-hacks/master/index.html
